# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontUpdated.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QTableWidgetItem

from modules.PipelineWallThickness.app import PipelineWindow
from modules.PipelineCrossingCalculation.ui_design.main_app import PipelineSimulationApp
from modules.PipelineOnBottomStability.OnBottomStability_main  import PipelineOnBottomStability
from database import create_table
from activity_logger import get_incomplete_modules
from PyQt5.QtWidgets import QMessageBox
from activity_logger import get_all_logs
from activity_logger import get_last_module_status





class MainSoftware(QMainWindow):
#     def setupUi(self, MainWindow):
    def __init__(self):
        super().__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.028, y1:0.0455909, x2:0.841, y2:0.966364, stop:0 rgba(169, 237, 255, 107), stop:0.994318 rgba(253, 255, 218, 255));")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Title = QtWidgets.QLabel(self.groupBox)
        self.label_Title.setText("")
        self.label_Title.setPixmap(QtGui.QPixmap("C:/Users/FARHEENKAIFEE/Desktop/SPIS LOGO (300 x 100 px) (0.95 x 0.55 in) (1).png"))
        self.label_Title.setScaledContents(True)
        self.label_Title.setWordWrap(True)
        self.label_Title.setObjectName("label_Title")
        self.gridLayout_2.addWidget(self.label_Title, 2, 0, 1, 1)
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_WallThickness = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_WallThickness.setEnabled(True)
        self.pushButton_WallThickness.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_WallThickness.setFont(font)
        self.pushButton_WallThickness.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_WallThickness.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_WallThickness.setAutoFillBackground(False)
        self.pushButton_WallThickness.setStyleSheet("background-color: #dbf3fa;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/wall thikcness.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_WallThickness.setIcon(icon)
        self.pushButton_WallThickness.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_WallThickness.setCheckable(False)
        self.pushButton_WallThickness.setAutoDefault(False)
        self.pushButton_WallThickness.setDefault(False)
        self.pushButton_WallThickness.setFlat(False)
        self.pushButton_WallThickness.setObjectName("pushButton_WallThickness")
        self.horizontalLayout.addWidget(self.pushButton_WallThickness)
        self.pushButton_Crossing = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Crossing.setEnabled(True)
        self.pushButton_Crossing.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Crossing.setFont(font)
        self.pushButton_Crossing.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_Crossing.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Crossing.setAutoFillBackground(False)
        self.pushButton_Crossing.setStyleSheet("background-color: #dbf3fa;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/pipelinecrossingcalculation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Crossing.setIcon(icon1)
        self.pushButton_Crossing.setIconSize(QtCore.QSize(54, 40))
        self.pushButton_Crossing.setCheckable(False)
        self.pushButton_Crossing.setAutoDefault(False)
        self.pushButton_Crossing.setDefault(False)
        self.pushButton_Crossing.setFlat(False)
        self.pushButton_Crossing.setObjectName("pushButton_Crossing")
        self.horizontalLayout.addWidget(self.pushButton_Crossing)
        self.pushButton_onbottom = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_onbottom.setEnabled(True)
        self.pushButton_onbottom.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_onbottom.setFont(font)
        self.pushButton_onbottom.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_onbottom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_onbottom.setAutoFillBackground(False)
        self.pushButton_onbottom.setStyleSheet("background-color: #dbf3fa;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/onbottomstability.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_onbottom.setIcon(icon2)
        self.pushButton_onbottom.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_onbottom.setCheckable(False)
        self.pushButton_onbottom.setAutoDefault(False)
        self.pushButton_onbottom.setDefault(False)
        self.pushButton_onbottom.setFlat(False)
        self.pushButton_onbottom.setObjectName("pushButton_onbottom")
        self.horizontalLayout.addWidget(self.pushButton_onbottom)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_frespananalysis = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_frespananalysis.setEnabled(True)
        self.pushButton_frespananalysis.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_frespananalysis.setFont(font)
        self.pushButton_frespananalysis.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_frespananalysis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_frespananalysis.setAutoFillBackground(False)
        self.pushButton_frespananalysis.setStyleSheet("background-color: #dbf3fa;\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/free-span.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_frespananalysis.setIcon(icon3)
        self.pushButton_frespananalysis.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_frespananalysis.setCheckable(False)
        self.pushButton_frespananalysis.setAutoDefault(False)
        self.pushButton_frespananalysis.setDefault(False)
        self.pushButton_frespananalysis.setFlat(False)
        self.pushButton_frespananalysis.setObjectName("pushButton_frespananalysis")
        self.horizontalLayout_2.addWidget(self.pushButton_frespananalysis)
        self.pushButton_PSI = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_PSI.setEnabled(True)
        self.pushButton_PSI.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_PSI.setFont(font)
        self.pushButton_PSI.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_PSI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_PSI.setAutoFillBackground(False)
        self.pushButton_PSI.setStyleSheet("background-color: #dbf3fa;\n"
"")
        self.pushButton_PSI.setIcon(icon1)
        self.pushButton_PSI.setIconSize(QtCore.QSize(54, 40))
        self.pushButton_PSI.setCheckable(False)
        self.pushButton_PSI.setAutoDefault(False)
        self.pushButton_PSI.setDefault(False)
        self.pushButton_PSI.setFlat(False)
        self.pushButton_PSI.setObjectName("pushButton_PSI")
        self.horizontalLayout_2.addWidget(self.pushButton_PSI)
        self.pushButton_onbottomroughness = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_onbottomroughness.setEnabled(True)
        self.pushButton_onbottomroughness.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_onbottomroughness.setFont(font)
        self.pushButton_onbottomroughness.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_onbottomroughness.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_onbottomroughness.setAutoFillBackground(False)
        self.pushButton_onbottomroughness.setStyleSheet("background-color: #dbf3fa;\n"
"")
        self.pushButton_onbottomroughness.setIcon(icon2)
        self.pushButton_onbottomroughness.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_onbottomroughness.setCheckable(False)
        self.pushButton_onbottomroughness.setAutoDefault(False)
        self.pushButton_onbottomroughness.setDefault(False)
        self.pushButton_onbottomroughness.setFlat(False)
        self.pushButton_onbottomroughness.setObjectName("pushButton_onbottomroughness")
        self.horizontalLayout_2.addWidget(self.pushButton_onbottomroughness)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.groupBox_logo = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_logo.sizePolicy().hasHeightForWidth())
        self.groupBox_logo.setSizePolicy(sizePolicy)
        self.groupBox_logo.setMinimumSize(QtCore.QSize(100, 50))
        self.groupBox_logo.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}\n"
"")
        self.groupBox_logo.setTitle("")
        self.groupBox_logo.setObjectName("groupBox_logo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_logo)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logoLabel = QtWidgets.QLabel(self.groupBox_logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 50))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("assets/Ashkam LOGO (1400 x 600 px).png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_3.addWidget(self.logoLabel)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_logo, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuModules = QtWidgets.QMenu(self.menubar)
        self.menuModules.setObjectName("menuModules")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Create progress bar (hidden initially)
        self.progress = QtWidgets.QProgressBar()
        self.progress.setMaximumWidth(180)
        self.progress.setRange(0, 0)  # Infinite animation
        self.progress.hide()
        self.statusbar.addPermanentWidget(self.progress)

        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionPipeline_Wall_Thickness = QtWidgets.QAction(MainWindow)
        self.actionPipeline_Wall_Thickness.setObjectName("actionPipeline_Wall_Thickness")
        self.actionPipeline_Crossing_Calculation = QtWidgets.QAction(MainWindow)
        self.actionPipeline_Crossing_Calculation.setObjectName("actionPipeline_Crossing_Calculation")
        self.menuEdit.addAction(self.actionReset)
        self.menuModules.addSeparator()
        self.menuModules.addAction(self.actionPipeline_Wall_Thickness)
        self.menuModules.addAction(self.actionPipeline_Crossing_Calculation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuModules.menuAction())

        self.label_copyright = QtWidgets.QLabel(self.groupBox)
        self.label_copyright.setObjectName("label_copyright")
        self.gridLayout_2.addWidget(self.label_copyright, 4, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_WallThickness.clicked.connect(self.openWallThickness)
        self.pushButton_Crossing.clicked.connect(self.openCrossingCalculations)
        self.pushButton_onbottom.clicked.connect(self.openOnBottomRoughness)


        create_table()
        
        
        
        
        
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_copyright.setText(_translate("MainWindow", "© 2026 Ashkam Energy Pvt. Ltd. All rights reserved "))
        self.pushButton_WallThickness.setText(_translate("MainWindow", "Pipeline Wall Thickness"))
        self.pushButton_Crossing.setText(_translate("MainWindow", "  Pipeline Crossing"))
        self.pushButton_onbottom.setText(_translate("MainWindow", "  On Bottom Stability"))
        self.pushButton_frespananalysis.setText(_translate("MainWindow", "Free Span Analysis"))
        self.pushButton_PSI.setText(_translate("MainWindow", "PSI"))
        self.pushButton_onbottomroughness.setText(_translate("MainWindow", "On Bottom Roughness"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuModules.setTitle(_translate("MainWindow", "Modules"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionPipeline_Wall_Thickness.setText(_translate("MainWindow", "Pipeline Wall Thickness"))
        self.actionPipeline_Crossing_Calculation.setText(_translate("MainWindow", "Pipeline Crossing Calculation"))
        
        


    def update_module_display(self):
        modules = [
            ("Wall Thickness", self.label_wall_last, self.label_wall_status),
            ("Stress Calc", self.label_stress_last, self.label_stress_status),
        ]

        for module_name, last_label, status_label in modules:
            data = get_last_module_status(module_name)

            if data:
                open_time, close_time, status = data

                last_label.setText(f"Last Open: {open_time}")
                status_label.setText(f"Status: {status}")

                if status == "OPEN":
                    status_label.setStyleSheet("color: red;")
                else:
                    status_label.setStyleSheet("color: green;")
            else:
                last_label.setText("No History")
                status_label.setText("")

    


    def update_button_text(self):
        data = get_last_module_status("Wall Thickness")

        if data:
            open_time, close_time, status = data

            self.pushButton_WallThickness.setText(
                f"Wall Thickness\n\nLast Open: {open_time}\nStatus: {status}"
            )

            if status == "OPEN":
                self.pushButton_WallThickness.setStyleSheet("color: red;")
            else:
                self.pushButton_WallThickness.setStyleSheet("color: green;")

        else:
            self.pushButton_WallThickness.setText("Wall Thickness\n\nNo History")
    


    def startLoading(self, message):
        self.statusbar.showMessage(message)
        self.progress.show()

    # Disable all buttons
        for btn in self.findChildren(QtWidgets.QPushButton):
            btn.setEnabled(False)

        QtWidgets.QApplication.processEvents()


    def stopLoading(self, message="Module Loaded Successfully"):
        self.progress.hide()
        self.statusbar.showMessage(message, 3000)

        # Re-enable buttons
        for btn in self.findChildren(QtWidgets.QPushButton):
            btn.setEnabled(True)


    def openWallThickness(self):
        self.startLoading("Opening Pipeline Wall Thickness... Please wait ⏳")
        QtCore.QTimer.singleShot(5000, self.launchWallThickness)  # 10000 ms = 10 sec
        

    def openCrossingCalculations(self):
        self.startLoading("Opening Pipeline Crossing Calculation... Please wait ⏳")
        QtCore.QTimer.singleShot(5000, self.launchCrossingCalculation)  # 10000 ms = 10 sec

    def openOnBottomRoughness(self):
        self.startLoading("Opening Pipeline On Bottom Stability... Please wait ⏳")
        QtCore.QTimer.singleShot(5000, self.launchOnBottomStability)  # 10000 ms = 10 sec
        


    def showLoadingMessage(self, text):
        self.statusbar.showMessage(text)
        QtWidgets.QApplication.processEvents()

    def launchWallThickness(self):
        self.pipeline = PipelineWindow()
        self.pipeline.show()
        self.statusbar.showMessage("Pipeline Wall Thickness Loaded ✅", 3000)
        self.stopLoading("Pipeline Wall Thickness Exiting")
        self.pipeline.moduleClosed.connect(self.update_button_text)

    def launchCrossingCalculation(self):
        self.pipeline2 = PipelineSimulationApp()
        self.pipeline2.show()
        self.statusbar.showMessage("Pipeline Crossing Calculation Loaded ✅", 3000)
        self.stopLoading("Pipeline Crossing Calculation Exiting")

    def launchOnBottomStability(self):
        self.pipeline3 = PipelineOnBottomStability()
        self.pipeline3.show()
        self.statusbar.showMessage("Pipeline On Bottom Stability Loaded ✅", 3000)
        self.stopLoading("Pipeline On Bottom Stability Exiting")

    def check_incomplete_modules(self):
        incomplete = get_incomplete_modules()

        if incomplete:
            message = ""
            for module_name, open_time in incomplete:
                message += f"{module_name} was not closed properly.\nOpened at: {open_time}\n\n"

            QMessageBox.warning(self, "Warning", message)

    def load_activity_table(self):
        logs = get_all_logs()

        self.tableWidget.setRowCount(len(logs))
        self.tableWidget.setColumnCount(5)

        self.tableWidget.setHorizontalHeaderLabels(
            ["ID", "Module", "Open Time", "Close Time", "Status"]
        )

        for row_number, row_data in enumerate(logs):
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(
                    row_number,
                    column_number,
                    QTableWidgetItem(str(data))
                )


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainSoftware()
#     ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
