# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton

from modules.PipelineWallThickness.app import PipelineWindow
from modules.PipelineCrossingCalculation.ui_design.main_app import PipelineSimulationApp
from modules.PipelineOnBottomStability.OnBottomStability_02_03_2026  import PipelineOnBottomStability


class MainSoftware(QMainWindow):
    # def setupUi(self, MainWindow):
    def __init__(self):
        super().__init__()

        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(700, 400)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.028, y1:0.0455909, x2:0.841, y2:0.966364, stop:0 rgba(169, 237, 255, 107), stop:0.994318 rgba(253, 255, 218, 255));")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(180, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(True)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuModules = QtWidgets.QMenu(self.menubar)
        self.menuModules.setObjectName("menuModules")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.setStatusBar(self.statusbar)
        self.statusbar.showMessage("Ready")

        # Create progress bar (hidden initially)
        self.progress = QtWidgets.QProgressBar()
        self.progress.setMaximumWidth(180)
        self.progress.setRange(0, 0)  # Infinite animation
        self.progress.hide()
        self.statusbar.addPermanentWidget(self.progress)
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionPipeline_Wall_Thickness = QtWidgets.QAction(MainWindow)
        self.actionPipeline_Wall_Thickness.setObjectName("actionPipeline_Wall_Thickness")
        self.actionPipeline_Crossing_Calculation = QtWidgets.QAction(MainWindow)
        self.actionPipeline_Crossing_Calculation.setObjectName("actionPipeline_Crossing_Calculation")
        self.menuEdit.addAction(self.actionReset)
        self.menuModules.addSeparator()
        self.menuModules.addAction(self.actionPipeline_Wall_Thickness)
        self.menuModules.addAction(self.actionPipeline_Crossing_Calculation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuModules.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.openWallThickness)
        self.pushButton_2.clicked.connect(self.openCrossingCalculations)
        self.pushButton_3.clicked.connect(self.openOnBottomRoughness)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Pipeline Wall Thickness"))
        self.pushButton_2.setText(_translate("MainWindow", "Pipeline Crossing Calculation"))
        self.pushButton_3.setText(_translate("MainWindow", "On Bottom Stability"))
        self.pushButton_4.setText(_translate("MainWindow", "Free Span Analysis"))
        self.pushButton_5.setText(_translate("MainWindow", "PSI"))
        self.pushButton_6.setText(_translate("MainWindow", "On Bottom Roughness"))
        self.label.setText(_translate("MainWindow", "SUBSEA PIPELINE INTEGRATED SOFTWARE"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuModules.setTitle(_translate("MainWindow", "Modules"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionPipeline_Wall_Thickness.setText(_translate("MainWindow", "Pipeline Wall Thickness"))
        self.actionPipeline_Crossing_Calculation.setText(_translate("MainWindow", "Pipeline Crossing Calculation"))


    def startLoading(self, message):
        self.statusbar.showMessage(message)
        self.progress.show()

    # Disable all buttons
        for btn in self.findChildren(QtWidgets.QPushButton):
            btn.setEnabled(False)

        QtWidgets.QApplication.processEvents()


    def stopLoading(self, message="Module Loaded Successfully"):
        self.progress.hide()
        self.statusbar.showMessage(message, 3000)

        # Re-enable buttons
        for btn in self.findChildren(QtWidgets.QPushButton):
            btn.setEnabled(True)


    def openWallThickness(self):
        self.startLoading("Opening Pipeline Wall Thickness... Please wait ⏳")
        QtCore.QTimer.singleShot(5000, self.launchWallThickness)  # 10000 ms = 10 sec
        

    def openCrossingCalculations(self):
        self.startLoading("Opening Pipeline Crossing Calculation... Please wait ⏳")
        QtCore.QTimer.singleShot(5000, self.launchCrossingCalculation)  # 10000 ms = 10 sec

    def openOnBottomRoughness(self):
        self.startLoading("Opening Pipeline On Bottom Stability... Please wait ⏳")
        QtCore.QTimer.singleShot(5000, self.launchOnBottomStability)  # 10000 ms = 10 sec
        


    def showLoadingMessage(self, text):
        self.statusbar.showMessage(text)
        QtWidgets.QApplication.processEvents()

    def launchWallThickness(self):
        self.pipeline = PipelineWindow()
        self.pipeline.show()
        self.statusbar.showMessage("Pipeline Wall Thickness Loaded ✅", 3000)
        self.stopLoading("Pipeline Wall Thickness Exiting")

    def launchCrossingCalculation(self):
        self.pipeline2 = PipelineSimulationApp()
        self.pipeline2.show()
        self.statusbar.showMessage("Pipeline Crossing Calculation Loaded ✅", 3000)
        self.stopLoading("Pipeline Crossing Calculation Exiting")

    def launchOnBottomStability(self):
        self.pipeline3 = PipelineOnBottomStability()
        self.pipeline3.show()
        self.statusbar.showMessage("Pipeline On Bottom Stability Loaded ✅", 3000)
        self.stopLoading("Pipeline On Bottom Stability Exiting")


if __name__ == "__main__":
   
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainSoftware()
    # ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


