from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime


def generate_pdf_report(input_data, output_data):
    filename = datetime.now().strftime("Pipeline_Report_%Y%m%d_%H%M%S.pdf")

    doc = SimpleDocTemplate(filename, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    # ---------------- TITLE ----------------
    elements.append(Paragraph("<b>Pipeline Crossing Simulation Report</b>", styles['Title']))
    elements.append(Spacer(1, 20))

    # ---------------- HEADER INFO ----------------
    header_data = [
        ["Project Title:", "Untitled Project (Initial)"],
        ["Report Date:", datetime.now().strftime("%B %d, %Y %H:%M:%S")],
        ["Generated By:", "User"],
        ["Verified By:", "_________________________"]
    ]

    header_table = Table(header_data, colWidths=[150, 300])
    header_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey)
    ]))

    elements.append(header_table)
    elements.append(Spacer(1, 20))

    # ---------------- INPUT TABLE ----------------
    elements.append(Paragraph("<b>1. Input Parameters</b>", styles['Heading2']))
    elements.append(Spacer(1, 10))

    input_table_data = [["Parameter", "Value", "Unit"]]

    for key, (value, unit) in input_data.items():
        input_table_data.append([key, str(value), unit])

    input_table = Table(input_table_data, colWidths=[200, 100, 100])
    input_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.25, colors.black),
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold')
    ]))

    elements.append(input_table)
    elements.append(Spacer(1, 20))

    # ---------------- OUTPUT TABLE ----------------
    elements.append(Paragraph("<b>2. Output Results</b>", styles['Heading2']))
    elements.append(Spacer(1, 10))

    output_table_data = [["Parameter", "Value"]]

    for key, value in output_data.items():
        output_table_data.append([key, str(value)])

    output_table = Table(output_table_data, colWidths=[250, 150])
    output_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.25, colors.black),
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold')
    ]))

    elements.append(output_table)

    # ---------------- BUILD PDF ----------------
    doc.build(elements)

    print(f"Report generated: {filename}")