# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OnBottomStability_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QMainWindow
import random
from calculations import lateralStability_installation
from calculations import lateralStability_operationContentFilled
from calculations import verticalStability_installationEmpty
from calculations import verticalStability_operationContentFilled
from calculations import verticalStability_operationShutDown
from calculations import other
import webbrowser
from PyQt5.QtWidgets import QMessageBox

from utils import caseOption, reset_all_inputs



frontendData = {}
saveData = {}




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        # MainWindow.resize(800, 500)
        MainWindow.resize(1000, 914)
        # MainWindow.resize(1271, 914)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../SPIS/assets/onbottomstability.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # type: ignore
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.028, y1:0.0455909, x2:0.841, y2:0.966364, stop:0 rgba(169, 237, 255, 107), stop:0.994318 rgba(253, 255, 218, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_Main = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Main.setTitle("On Bottom Stability")
        self.groupBox_Main.setObjectName("groupBox_Main")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_Main)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem = QtWidgets.QSpacerItem(20, 797, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem, 0, 1, 5, 1)
        self.groupBox_selection = QtWidgets.QGroupBox(self.groupBox_Main)
        self.groupBox_selection.setAutoFillBackground(False)
        self.groupBox_selection.setTitle("SELECTION SECTION")
        self.groupBox_selection.setObjectName("groupBox_selection")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_selection)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_select1 = QtWidgets.QLabel(self.groupBox_selection)
        self.label_select1.setObjectName("label_select1")
        self.horizontalLayout_2.addWidget(self.label_select1)
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_selection)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_1)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ProjectName = QtWidgets.QLabel(self.groupBox_selection)
        self.label_ProjectName.setObjectName("label_ProjectName")
        self.horizontalLayout_3.addWidget(self.label_ProjectName)
        self.lineEdit_ProjectName = QtWidgets.QLineEdit(self.groupBox_selection)
        self.lineEdit_ProjectName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_ProjectName.setObjectName("lineEdit_ProjectName")
        self.horizontalLayout_3.addWidget(self.lineEdit_ProjectName)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_DocNo = QtWidgets.QLabel(self.groupBox_selection)
        self.label_DocNo.setObjectName("label_DocNo")
        self.horizontalLayout_4.addWidget(self.label_DocNo)
        self.lineEdit_DocNo = QtWidgets.QLineEdit(self.groupBox_selection)
        self.lineEdit_DocNo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_DocNo.setObjectName("lineEdit_DocNo")
        self.horizontalLayout_4.addWidget(self.lineEdit_DocNo)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 0, 3, 2, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_selectCase = QtWidgets.QLabel(self.groupBox_selection)
        self.label_selectCase.setObjectName("label_selectCase")
        self.horizontalLayout_8.addWidget(self.label_selectCase)
        self.combobox_selectCase = QtWidgets.QComboBox(self.groupBox_selection)
        self.combobox_selectCase.setObjectName("combobox_selectCase")
        self.combobox_selectCase.addItem("")
        self.combobox_selectCase.addItem("")
        self.horizontalLayout_8.addWidget(self.combobox_selectCase)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_8) # type: ignore
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_PipeGrade = QtWidgets.QLabel(self.groupBox_selection)
        self.label_PipeGrade.setObjectName("label_PipeGrade")
        self.horizontalLayout.addWidget(self.label_PipeGrade)
        self.comboBox_pipeGrade = QtWidgets.QComboBox(self.groupBox_selection)
        self.comboBox_pipeGrade.setObjectName("comboBox_pipeGrade")
        self.comboBox_pipeGrade.addItem("")
        self.comboBox_pipeGrade.addItem("")
        self.comboBox_pipeGrade.addItem("")
        self.comboBox_pipeGrade.addItem("")
        self.comboBox_pipeGrade.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_pipeGrade)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9) # type: ignore
        self.gridLayout_9.addLayout(self.formLayout_2, 1, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 1, 2, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_selection, 0, 0, 1, 1)
        self.groupBox_checksContainer = QtWidgets.QGroupBox(self.groupBox_Main)
        self.groupBox_checksContainer.setTitle("CHECKS SECTION")
        self.groupBox_checksContainer.setFixedSize(1300, 110)
        self.groupBox_checksContainer.setObjectName("groupBox_checksContainer")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_checksContainer)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(20, 79, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(650, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 1, 1, 2, 1)
        self.result_display_label = QtWidgets.QLabel(self.groupBox_checksContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_display_label.sizePolicy().hasHeightForWidth())
        self.result_display_label.setSizePolicy(sizePolicy)
        self.result_display_label.setMaximumSize(QtCore.QSize(1000, 501))
        self.result_display_label.setObjectName("result_display_label")
        self.gridLayout_8.addWidget(self.result_display_label, 2, 0, 1, 1)
        self.groupBox_checks = QtWidgets.QWidget(self.groupBox_checksContainer)
        self.groupBox_checks.setObjectName("groupBox_checks")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_checks)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.Criteria1_label = QtWidgets.QLabel(self.groupBox_checks)
        self.Criteria1_label.setObjectName("Criteria1_label")
        self.horizontalLayout_70.addWidget(self.Criteria1_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_70.addItem(spacerItem6)
        self.Criteria1_lineEdit = QtWidgets.QLineEdit(self.groupBox_checks)
        self.Criteria1_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Criteria1_lineEdit.setObjectName("Criteria1_lineEdit")
        self.horizontalLayout_70.addWidget(self.Criteria1_lineEdit)
        self.gridLayout_22.addLayout(self.horizontalLayout_70, 0, 0, 1, 1)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.Criteria2_label = QtWidgets.QLabel(self.groupBox_checks)
        self.Criteria2_label.setObjectName("Criteria2_label")
        self.horizontalLayout_71.addWidget(self.Criteria2_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem7)
        self.Criteria2_lineEdit = QtWidgets.QLineEdit(self.groupBox_checks)
        self.Criteria2_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Criteria2_lineEdit.setObjectName("Criteria2_lineEdit")
        self.horizontalLayout_71.addWidget(self.Criteria2_lineEdit)
        self.gridLayout_22.addLayout(self.horizontalLayout_71, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_22, 1, 0, 2, 1)
        self.pushButton_check = QtWidgets.QPushButton(self.groupBox_checks)
        self.pushButton_check.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.pushButton_check.setObjectName("pushButton_check")
        self.gridLayout.addWidget(self.pushButton_check, 2, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(406, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 1, 1, 1, 2)
        # self.checks_label = QtWidgets.QLabel(self.groupBox_checks)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # font.setBold(True)
        # font.setWeight(75)
        # self.checks_label.setFont(font)
        # self.checks_label.setObjectName("checks_label")
        # self.gridLayout.addWidget(self.checks_label, 0, 0, 1, 3)
        self.gridLayout_8.addWidget(self.groupBox_checks, 0, 0, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_checksContainer, 4, 0, 1, 1)
        self.groupBox_InputContainer = QtWidgets.QGroupBox(self.groupBox_Main)
        self.groupBox_InputContainer.setTitle("INPUTS SECTION")
        self.groupBox_InputContainer.setFixedSize(1300, 190)
        self.groupBox_InputContainer.setObjectName("groupBox_InputContainer")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_InputContainer)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_run = QtWidgets.QPushButton(self.groupBox_InputContainer)
        self.pushButton_run.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout_13.addWidget(self.pushButton_run, 1, 1, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 256, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(571, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem11, 1, 0, 1, 1)
        self.groupBox_inputData = QtWidgets.QWidget(self.groupBox_InputContainer)
        self.groupBox_inputData.setObjectName("groupBox_inputData")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_inputData)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.Hs_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.Hs_label.setObjectName("Hs_label")
        self.horizontalLayout_75.addWidget(self.Hs_label)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem12)
        self.Hs_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.Hs_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Hs_lineEdit.setObjectName("Hs_lineEdit")
        self.horizontalLayout_75.addWidget(self.Hs_lineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_75, 0, 0, 1, 1)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.Tp_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.Tp_label.setObjectName("Tp_label")
        self.horizontalLayout_76.addWidget(self.Tp_label)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem14)
        self.Tp_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.Tp_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tp_lineEdit.setObjectName("Tp_lineEdit")
        self.horizontalLayout_76.addWidget(self.Tp_lineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_76, 1, 0, 1, 1)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.d_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.d_label.setObjectName("d_label")
        self.horizontalLayout_77.addWidget(self.d_label)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem16)
        self.d_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.d_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_lineEdit.setObjectName("d_lineEdit")
        self.horizontalLayout_77.addWidget(self.d_lineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_77, 2, 0, 1, 1)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.related_angle_theta_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.related_angle_theta_label.setObjectName("related_angle_theta_label")
        self.horizontalLayout_79.addWidget(self.related_angle_theta_label)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_79.addItem(spacerItem17)
        self.related_angle_theta_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.related_angle_theta_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.related_angle_theta_lineEdit.setObjectName("related_angle_theta_lineEdit")
        self.horizontalLayout_79.addWidget(self.related_angle_theta_lineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_79, 3, 0, 1, 1)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.zr_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.zr_label.setObjectName("zr_label")
        self.horizontalLayout_80.addWidget(self.zr_label)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_80.addItem(spacerItem18)
        self.zr_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.zr_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.zr_lineEdit.setObjectName("zr_lineEdit")
        self.horizontalLayout_80.addWidget(self.zr_lineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_80, 4, 0, 1, 1)
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.ys_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.ys_label.setObjectName("ys_label")
        self.horizontalLayout_81.addWidget(self.ys_label)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_81.addItem(spacerItem19)
        self.ys_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.ys_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ys_lineEdit.setObjectName("ys_lineEdit")
        self.horizontalLayout_81.addWidget(self.ys_lineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_81, 5, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 4, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem20, 0, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.mg_thickness_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.mg_thickness_label.setObjectName("mg_thickness_label")
        self.horizontalLayout_73.addWidget(self.mg_thickness_label)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_73.addItem(spacerItem21)
        self.mg_thickness_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.mg_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mg_thickness_lineEdit.setObjectName("mg_thickness_lineEdit")
        self.horizontalLayout_73.addWidget(self.mg_thickness_lineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_73, 4, 0, 1, 1)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.rho_cont_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.rho_cont_label.setObjectName("rho_cont_label")
        self.horizontalLayout_53.addWidget(self.rho_cont_label)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem22)
        self.rho_cont_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.rho_cont_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rho_cont_lineEdit.setObjectName("rho_cont_lineEdit")
        self.horizontalLayout_53.addWidget(self.rho_cont_lineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_53, 1, 0, 1, 1)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.rho_c_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.rho_c_label.setObjectName("rho_c_label")
        self.horizontalLayout_50.addWidget(self.rho_c_label)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem23)
        self.rho_c_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.rho_c_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rho_c_lineEdit.setObjectName("rho_c_lineEdit")
        self.horizontalLayout_50.addWidget(self.rho_c_lineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_50, 0, 0, 1, 1)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.yw_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.yw_label.setObjectName("yw_label")
        self.horizontalLayout_51.addWidget(self.yw_label)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem24)
        self.yw_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.yw_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.yw_lineEdit.setObjectName("yw_lineEdit")
        self.horizontalLayout_51.addWidget(self.yw_lineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_51, 2, 0, 1, 1)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.mg_density_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.mg_density_label.setObjectName("mg_density_label")
        self.horizontalLayout_72.addWidget(self.mg_density_label)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_72.addItem(spacerItem25)
        self.mg_density_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.mg_density_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mg_density_lineEdit.setObjectName("mg_density_lineEdit")
        self.horizontalLayout_72.addWidget(self.mg_density_lineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_72, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.rho_HDPE_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.rho_HDPE_label.setObjectName("rho_HDPE_label")
        self.horizontalLayout_48.addWidget(self.rho_HDPE_label)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem26)
        self.rho_HDPE_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.rho_HDPE_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rho_HDPE_lineEdit.setObjectName("rho_HDPE_lineEdit")
        self.horizontalLayout_48.addWidget(self.rho_HDPE_lineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_48, 0, 0, 1, 1)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.OD_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.OD_label.setObjectName("OD_label")
        self.horizontalLayout_45.addWidget(self.OD_label)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem27)
        self.OD_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.OD_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OD_lineEdit.setObjectName("OD_lineEdit")
        self.horizontalLayout_45.addWidget(self.OD_lineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_45, 1, 0, 1, 1)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.tHDPE_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.tHDPE_label.setObjectName("tHDPE_label")
        self.horizontalLayout_44.addWidget(self.tHDPE_label)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem28)
        self.tHDPE_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.tHDPE_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tHDPE_lineEdit.setObjectName("tHDPE_lineEdit")
        self.horizontalLayout_44.addWidget(self.tHDPE_lineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_44, 2, 0, 1, 1)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.concrete_coating_thickness_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.concrete_coating_thickness_label.setObjectName("concrete_coating_thickness_label")
        self.horizontalLayout_46.addWidget(self.concrete_coating_thickness_label)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem29)
        self.concrete_coating_thickness_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.concrete_coating_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.concrete_coating_thickness_lineEdit.setObjectName("concrete_coating_thickness_lineEdit")
        self.horizontalLayout_46.addWidget(self.concrete_coating_thickness_lineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_46, 3, 0, 1, 1)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.CA_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.CA_label.setObjectName("CA_label")
        self.horizontalLayout_47.addWidget(self.CA_label)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem30)
        self.CA_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.CA_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CA_lineEdit.setObjectName("CA_lineEdit")
        self.horizontalLayout_47.addWidget(self.CA_lineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_47, 4, 0, 1, 1)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.Vc_label = QtWidgets.QLabel(self.groupBox_inputData)
        self.Vc_label.setObjectName("Vc_label")
        self.horizontalLayout_49.addWidget(self.Vc_label)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem31)
        self.Vc_lineEdit = QtWidgets.QLineEdit(self.groupBox_inputData)
        self.Vc_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Vc_lineEdit.setObjectName("Vc_lineEdit")
        self.horizontalLayout_49.addWidget(self.Vc_lineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_49, 5, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem32, 0, 3, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(20, 234, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem33, 1, 1, 1, 1)
        # self.label_INPUT_Data = QtWidgets.QLabel(self.groupBox_inputData)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # font.setBold(True)
        # font.setUnderline(False)
        # font.setWeight(75)
        # self.label_INPUT_Data.setFont(font)
        # self.label_INPUT_Data.setObjectName("label_INPUT_Data")
        # self.gridLayout_12.addWidget(self.label_INPUT_Data, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_inputData, 0, 0, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_InputContainer, 1, 0, 1, 1)
        self.groupBox_resultContainer = QtWidgets.QGroupBox(self.groupBox_Main)
        self.groupBox_resultContainer.setTitle("RESULT SECTION")
        self.groupBox_resultContainer.setFixedSize(1300, 165)
        self.groupBox_resultContainer.setObjectName("groupBox_resultContainer")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_resultContainer)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_result = QtWidgets.QWidget(self.groupBox_resultContainer)
        self.groupBox_result.setObjectName("groupBox_result")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_result)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.VID_label_54 = QtWidgets.QLabel(self.groupBox_result)
        self.VID_label_54.setObjectName("VID_label_54")
        self.horizontalLayout_55.addWidget(self.VID_label_54)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem34)
        self.VID_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.VID_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VID_lineEdit.setObjectName("VID_lineEdit")
        self.horizontalLayout_55.addWidget(self.VID_lineEdit)
        self.gridLayout_17.addLayout(self.horizontalLayout_55, 3, 0, 1, 1)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.AID_label = QtWidgets.QLabel(self.groupBox_result)
        self.AID_label.setObjectName("AID_label")
        self.horizontalLayout_56.addWidget(self.AID_label)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem35)
        self.AID_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.AID_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AID_lineEdit.setObjectName("AID_lineEdit")
        self.horizontalLayout_56.addWidget(self.AID_lineEdit)
        self.gridLayout_17.addLayout(self.horizontalLayout_56, 2, 0, 1, 1)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.VOD_label = QtWidgets.QLabel(self.groupBox_result)
        self.VOD_label.setObjectName("VOD_label")
        self.horizontalLayout_57.addWidget(self.VOD_label)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem36)
        self.VOD_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.VOD_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VOD_lineEdit.setObjectName("VOD_lineEdit")
        self.horizontalLayout_57.addWidget(self.VOD_lineEdit)
        self.gridLayout_17.addLayout(self.horizontalLayout_57, 1, 0, 1, 1)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.At_label = QtWidgets.QLabel(self.groupBox_result)
        self.At_label.setObjectName("At_label")
        self.horizontalLayout_58.addWidget(self.At_label)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem37)
        self.At_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.At_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.At_lineEdit.setObjectName("At_lineEdit")
        self.horizontalLayout_58.addWidget(self.At_lineEdit)
        self.gridLayout_17.addLayout(self.horizontalLayout_58, 4, 0, 1, 1)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.AOD_label = QtWidgets.QLabel(self.groupBox_result)
        self.AOD_label.setObjectName("AOD_label")
        self.horizontalLayout_59.addWidget(self.AOD_label)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem38)
        self.AOD_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.AOD_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AOD_lineEdit.setObjectName("AOD_lineEdit")
        self.horizontalLayout_59.addWidget(self.AOD_lineEdit)
        self.gridLayout_17.addLayout(self.horizontalLayout_59, 0, 0, 1, 1)
        self.horizontalLayout_54.addLayout(self.gridLayout_17)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem39)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.Vt_label = QtWidgets.QLabel(self.groupBox_result)
        self.Vt_label.setObjectName("Vt_label")
        self.horizontalLayout_60.addWidget(self.Vt_label)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem40)
        self.Vt_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Vt_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Vt_lineEdit.setObjectName("Vt_lineEdit")
        self.horizontalLayout_60.addWidget(self.Vt_lineEdit)
        self.gridLayout_18.addLayout(self.horizontalLayout_60, 0, 0, 1, 1)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.Msea_water_label = QtWidgets.QLabel(self.groupBox_result)
        self.Msea_water_label.setObjectName("Msea_water_label")
        self.horizontalLayout_61.addWidget(self.Msea_water_label)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem41)
        self.Msea_water_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Msea_water_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msea_water_lineEdit.setObjectName("Msea_water_lineEdit")
        self.horizontalLayout_61.addWidget(self.Msea_water_lineEdit)
        self.gridLayout_18.addLayout(self.horizontalLayout_61, 2, 0, 1, 1)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.M_pipe_label = QtWidgets.QLabel(self.groupBox_result)
        self.M_pipe_label.setObjectName("M_pipe_label")
        self.horizontalLayout_62.addWidget(self.M_pipe_label)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem42)
        self.Mpipe_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Mpipe_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Mpipe_lineEdit.setObjectName("Mpipe_lineEdit")
        self.horizontalLayout_62.addWidget(self.Mpipe_lineEdit)
        self.gridLayout_18.addLayout(self.horizontalLayout_62, 1, 0, 1, 1)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.Bpipe_label = QtWidgets.QLabel(self.groupBox_result)
        self.Bpipe_label.setObjectName("Bpipe_label")
        self.horizontalLayout_63.addWidget(self.Bpipe_label)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem43)
        self.Bpipe_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Bpipe_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Bpipe_lineEdit.setObjectName("Bpipe_lineEdit")
        self.horizontalLayout_63.addWidget(self.Bpipe_lineEdit)
        self.gridLayout_18.addLayout(self.horizontalLayout_63, 3, 0, 1, 1)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.Mc_label = QtWidgets.QLabel(self.groupBox_result)
        self.Mc_label.setObjectName("Mc_label")
        self.horizontalLayout_64.addWidget(self.Mc_label)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem44)
        self.Mc_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Mc_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Mc_lineEdit.setObjectName("Mc_lineEdit")
        self.horizontalLayout_64.addWidget(self.Mc_lineEdit)
        self.gridLayout_18.addLayout(self.horizontalLayout_64, 4, 0, 1, 1)
        self.horizontalLayout_54.addLayout(self.gridLayout_18)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem45)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.Wp_label = QtWidgets.QLabel(self.groupBox_result)
        self.Wp_label.setObjectName("Wp_label")
        self.horizontalLayout_65.addWidget(self.Wp_label)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem46)
        self.Wp_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Wp_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Wp_lineEdit.setObjectName("Wp_lineEdit")
        self.horizontalLayout_65.addWidget(self.Wp_lineEdit)
        self.gridLayout_19.addLayout(self.horizontalLayout_65, 1, 0, 1, 1)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.Bc_label = QtWidgets.QLabel(self.groupBox_result)
        self.Bc_label.setObjectName("Bc_label")
        self.horizontalLayout_66.addWidget(self.Bc_label)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem47)
        self.Bc_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Bc_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Bc_lineEdit.setObjectName("Bc_lineEdit")
        self.horizontalLayout_66.addWidget(self.Bc_lineEdit)
        self.gridLayout_19.addLayout(self.horizontalLayout_66, 0, 0, 1, 1)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.Wc_label = QtWidgets.QLabel(self.groupBox_result)
        self.Wc_label.setObjectName("Wc_label")
        self.horizontalLayout_67.addWidget(self.Wc_label)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem48)
        self.Wc_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Wc_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Wc_lineEdit.setObjectName("Wc_lineEdit")
        self.horizontalLayout_67.addWidget(self.Wc_lineEdit)
        self.gridLayout_19.addLayout(self.horizontalLayout_67, 2, 0, 1, 1)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.SG_label = QtWidgets.QLabel(self.groupBox_result)
        self.SG_label.setObjectName("SG_label")
        self.horizontalLayout_68.addWidget(self.SG_label)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_68.addItem(spacerItem49)
        self.SG_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.SG_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SG_lineEdit.setObjectName("SG_lineEdit")
        self.horizontalLayout_68.addWidget(self.SG_lineEdit)
        self.gridLayout_19.addLayout(self.horizontalLayout_68, 4, 0, 1, 1)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.Ws_label = QtWidgets.QLabel(self.groupBox_result)
        self.Ws_label.setObjectName("Ws_label")
        self.horizontalLayout_69.addWidget(self.Ws_label)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem50)
        self.Ws_lineEdit = QtWidgets.QLineEdit(self.groupBox_result)
        self.Ws_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Ws_lineEdit.setObjectName("Ws_lineEdit")
        self.horizontalLayout_69.addWidget(self.Ws_lineEdit)
        self.gridLayout_19.addLayout(self.horizontalLayout_69, 3, 0, 1, 1)
        self.horizontalLayout_54.addLayout(self.gridLayout_19)
        self.gridLayout_3.addLayout(self.horizontalLayout_54, 1, 0, 1, 1)
        # self.Label_Result = QtWidgets.QLabel(self.groupBox_result)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # font.setBold(True)
        # font.setWeight(75)
        # self.Label_Result.setFont(font)
        # self.Label_Result.setObjectName("Label_Result")
        # self.gridLayout_3.addWidget(self.Label_Result, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_result, 0, 0, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(20, 233, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem51, 0, 1, 1, 1)
        spacerItem52 = QtWidgets.QSpacerItem(846, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem52, 1, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_resultContainer, 2, 0, 1, 1)
        self.groupBox_progressBar = QtWidgets.QGroupBox(self.groupBox_Main)
        self.groupBox_progressBar.setTitle("PROGRESS DISPLAY")
        self.groupBox_progressBar.setFixedSize(1290, 40)
        self.groupBox_progressBar.setObjectName("groupBox_progressBar")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_progressBar)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_progressBar)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setFixedSize(1250, 10)
        self.gridLayout_15.addWidget(self.progressBar, 0, 0, 0, 0)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem53, 0, 0, 1, 1)
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem54, 0, 1, 1, 1)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem55, 0, 2, 1, 1)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem56, 0, 3, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_progressBar, 5, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_Main, 0, 0, 1, 2)
        spacerItem57 = QtWidgets.QSpacerItem(944, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem57, 1, 1, 1, 1)
        spacerItem58 = QtWidgets.QSpacerItem(20, 1012, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem58, 0, 2, 1, 1)
        self.label_copyright = QtWidgets.QLabel(self.centralwidget)
        self.label_copyright.setObjectName("label_copyright")
        self.gridLayout_11.addWidget(self.label_copyright, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1271, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../SPIS/assets/open.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # type: ignore
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../SPIS/assets/save_as.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # type: ignore
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../SPIS/assets/close.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # pyright: ignore[reportAttributeAccessIssue]
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../SPIS/assets/reset.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # type: ignore
        self.actionReset.setIcon(icon4)
        self.actionReset.setObjectName("actionReset")
        self.actionGenerate_Report = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../SPIS/assets/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # type: ignore
        self.actionGenerate_Report.setIcon(icon5)
        self.actionGenerate_Report.setObjectName("actionGenerate_Report")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../SPIS/assets/report.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # type: ignore
        self.actionDocumentation.setIcon(icon6)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionWhat_s_New = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../SPIS/assets/What\'s new.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off) # type: ignore
        self.actionWhat_s_New.setIcon(icon7)
        self.actionWhat_s_New.setObjectName("actionWhat_s_New")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionReset)
        self.menuReport.addAction(self.actionGenerate_Report)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionWhat_s_New)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #  hiding the result label to triggere it from check push button  

        self.result_display_label.hide()
        
# -----------------------------FUNCTION ARE FROM HERE---------------------------------------------------------------------
       

        self.pushButton_run.clicked.connect(self.inputData)
        self.pushButton_check.clicked.connect(self.EnableResultLabel)
        
        #comboBox functions
        self.comboBox_1.currentTextChanged.connect(self.changeComboBoxCase)
        self.combobox_selectCase.currentTextChanged.connect(self.selectAnalysis)
        
        
        # Menu bar functions
        self.actionReset.triggered.connect(self.reset_all)
        self.actionSave_As.triggered.connect(self.save_As)
        self.actionOpen.triggered.connect(self.openFile)
        self.actionGenerate_Report.triggered.connect(self.generate_report)
        self.actionDocumentation.triggered.connect(self.open_documentation)
        self.actionWhat_s_New.triggered.connect(self.open_whats_new)
        
        
        
        
        
    # def open_documentation(self):
        # url = "https://www.google.com"  # Replace with your documentation URL
        # webbrowser.open(url)
        # print("Documentation button clicked")
        
        
        
        
        
    
        
        
        

        
        
    #  function which changes the items in second combobox_selectCase   
    def changeComboBoxCase(self, text):
        print("Hello")
        print(text)
        self.combobox_selectCase.blockSignals(True)
        self.combobox_selectCase.clear()
        print("comboBox is cleared now")
        
        options = caseOption.get(text,[]) #caseOption is imported from utils.
        print(options)
        
        self.combobox_selectCase.addItems(options)
        self.combobox_selectCase.blockSignals(False)

    def selectAnalysis(self, text):
        print("Selected case:", text)



    def inputData(self):

        try:

            analysis_type = self.comboBox_1.currentText()
            selected_case = self.combobox_selectCase.currentText()

            print("Analysis:", analysis_type)
            print("Case:", selected_case)

            # ----------- LATERAL STABILITY -----------
            if analysis_type == "Lateral Stability":

                frontendData = {
                    "HDPE_density_rho_HDPE": float(self.rho_HDPE_lineEdit.text()),
                    "Outside_diameter_OD": float(self.OD_lineEdit.text()),
                    "Concrete_Coating_thickness_t_cc": float(self.concrete_coating_thickness_lineEdit.text()),
                    "Wall_Thickness_t_HDPE": float(self.tHDPE_lineEdit.text()),
                    "Volume_of_Concrete_per_meter_of_pipe_Vc": float(self.Vc_lineEdit.text()),
                    "Marine_growth_Thickness_t_mg": float(self.mg_thickness_lineEdit.text()),
                    "Marine_growth_density_rho_mg": float(self.mg_density_lineEdit.text()),
                    "Content_density_seawater_rho_cont": float(self.rho_cont_lineEdit.text()),
                    "Safety_factor_for_weight_gamma_w": float(self.yw_lineEdit.text()),
                    "Significant_wave_height_Hs": float(self.Hs_lineEdit.text()),
                    "Spectral_peak_period_Tp": float(self.Tp_lineEdit.text()),
                    "Water_depth_d": float(self.d_lineEdit.text()),
                    "Related_angle_btw_pipeline_and_current_direction_teta": float(self.related_angle_theta_lineEdit.text()),
                    "Ref_major_height_above_the_seabed_zr": float(self.zr_lineEdit.text()),
                }

                if selected_case == "Installation-Empty":
                    result = lateralStability_installation(frontendData)

                elif selected_case == "Operation-Content Filled":
                    result = lateralStability_operationContentFilled(frontendData)

                else:
                    print("Invalid lateral case")
                    return

                self.displayLateralResults(result)

                
                self.Criteria1_label.setText("Criteria 1")
                self.Criteria2_lineEdit.show()
                self.Criteria2_label.show()

                self.result_display_label.setText(
                        f"Lateral Stability : {result['LSC_min']} | {result['LSC_min1']}"
                    )


                


            # ----------- VERTICAL STABILITY -----------
            elif analysis_type == "Vertical Stability":

                frontendData = {
                    "rh_HDPE": float(self.rho_HDPE_lineEdit.text()),
                    "OD": float(self.OD_lineEdit.text()),
                    "t_HDPE": float(self.tHDPE_lineEdit.text()),
                    "CA": float(self.CA_lineEdit.text()),
                    "V_c": float(self.Vc_lineEdit.text()),
                    "rh_cont": float(self.rho_cont_lineEdit.text()),
                    "gamma_w": float(self.yw_lineEdit.text()),
                }

                if selected_case == "Installation-Empty":
                    result = verticalStability_installationEmpty(frontendData)

                elif selected_case == "Operation-Content Filled":
                    result = verticalStability_operationContentFilled(frontendData)

                elif selected_case == "Operation-Shutdown-Empty":
                    result = verticalStability_operationShutDown(frontendData)

                else:
                    print("Invalid vertical case")
                    return

                self.displayVerticalResults(result)
                
                self.Criteria1_label.setText("UC check")
                self.Criteria2_lineEdit.hide()
                self.Criteria2_label.hide()
                self.result_display_label.setText(
                    f"Vertical Stability : {result['UC_status']}"
                )

        except Exception as e:
            print(f"error code:{random.random()}>>>>>>{e}")
            
            
    
    
    def reset_all(self, MainWindow):
        print("Started Resetting all inputs now.............WAIT!")
        try:
            # Reset all input fields
            self.rho_HDPE_lineEdit.clear()
            self.OD_lineEdit.clear()
            self.concrete_coating_thickness_lineEdit.clear()
            self.tHDPE_lineEdit.clear()
            self.CA_lineEdit.clear()
            self.Vc_lineEdit.clear()
            self.rho_c_lineEdit.clear()
            self.mg_thickness_lineEdit.clear()
            self.mg_density_lineEdit.clear()
            self.rho_cont_lineEdit.clear()
            self.yw_lineEdit.clear()
            self.Hs_lineEdit.clear()
            self.Tp_lineEdit.clear()
            self.d_lineEdit.clear()
            self.related_angle_theta_lineEdit.clear()
            self.zr_lineEdit.clear()
            self.ys_lineEdit.clear()

            # Reset result fields
            self.AOD_lineEdit.clear()
            self.VOD_lineEdit.clear()
            self.AID_lineEdit.clear()
            self.VID_lineEdit.clear()
            self.At_lineEdit.clear()
            self.Vt_lineEdit.clear()
            self.Mpipe_lineEdit.clear()
            self.Msea_water_lineEdit.clear()
            self.Bpipe_lineEdit.clear()
            self.Mc_lineEdit.clear()
            self.Bc_lineEdit.clear()
            self.Wp_lineEdit.clear()
            self.Wc_lineEdit.clear()
            self.Ws_lineEdit.clear()
            self.SG_lineEdit.clear()
            
            # Result criteria fields
            self.Criteria1_lineEdit.clear()
            self.Criteria2_lineEdit.clear()

            # Reset result display label
            self.result_display_label.setText("------------Reset Completed------------")
            print("Resetting completed successfully!")
        except Exception as e:
            print(f"Error during reset: {e}")
            print("Resetting failed. Please try again.")
            self.result_display_label.setText("Resetting failed. Please try again.")
    
    
    def save_As(self, MainWindow):
        print("Save As functionality is initialized")
        self.result_display_label.setText("Save As functionality is not implemented yet.")
        
        # Reset all input fields
            # self.rho_HDPE_lineEdit.clear()
            # self.OD_lineEdit.clear()
            # self.concrete_coating_thickness_lineEdit.clear()
            # self.tHDPE_lineEdit.clear()
            # self.CA_lineEdit.clear()
            # self.Vc_lineEdit.clear()
            # self.rho_c_lineEdit.clear()
            # self.mg_thickness_lineEdit.clear()
            # self.mg_density_lineEdit.clear()
            # self.rho_cont_lineEdit.clear()
            # self.yw_lineEdit.clear()
            # self.Hs_lineEdit.clear()
            # self.Tp_lineEdit.clear()
            # self.d_lineEdit.clear()
            # self.related_angle_theta_lineEdit.clear()
            # self.zr_lineEdit.clear()
            # self.ys_lineEdit.clear()

            # # Reset result fields
            # self.AOD_lineEdit.clear()
            # self.VOD_lineEdit.clear()
            # self.AID_lineEdit.clear()
            # self.VID_lineEdit.clear()
            # self.At_lineEdit.clear()
            # self.Vt_lineEdit.clear()
            # self.Mpipe_lineEdit.clear()
            # self.Msea_water_lineEdit.clear()
            # self.Bpipe_lineEdit.clear()
            # self.Mc_lineEdit.clear()
            # self.Bc_lineEdit.clear()
            # self.Wp_lineEdit.clear()
            # self.Wc_lineEdit.clear()
            # self.Ws_lineEdit.clear()
            # self.SG_lineEdit.clear()
            
            # # Result criteria fields
            # self.Criteria1_lineEdit.clear()
            # self.Criteria2_lineEdit.clear()
        # try:
            # saveData = {
            #     "HDPE_density_rho_HDPE": float(self.rho_HDPE_lineEdit.text()),
            #     "Outside_diameter_OD": float(self.OD_lineEdit.text()),
            #     "Concrete_Coating_thickness_t_cc": float(self.concrete_coating_thickness_lineEdit.text()),
            #     "Wall_Thickness_t_HDPE": float(self.tHDPE_lineEdit.text()),
            #     "Volume_of_Concrete_per_meter_of_pipe_Vc": float(self.Vc_lineEdit.text()),
            #     "Marine_growth_Thickness_t_mg": float(self.mg_thickness_lineEdit.text()),
            #     "Marine_growth_density_rho_mg": float(self.mg_density_lineEdit.text()),
            #     "Content_density_seawater_rho_cont": float(self.rho_cont_lineEdit.text()),
            #     "Safety_factor_for_weight_gamma_w": float(self.yw_lineEdit.text()),
            #     "Significant_wave_height_Hs": float(self.Hs_lineEdit.text()),
            #     "Spectral_peak_period_Tp": float(self.Tp_lineEdit.text()),
            #     "Water_depth_d": float(self.d_lineEdit.text()),
            #     "Related_angle_btw_pipeline_and_current_direction_teta": float(self.related_angle_theta_lineEdit.text()),
            #     "Ref_major_height_above_the_seabed_zr": float(self.zr_lineEdit.text()),
                # "Submerged_Soil_Weight_for_Sand_ys": float(self.ys_lineEdit.text()),
            # }
            # Here you can implement the logic to save saveData to a file (e.g., JSON, CSV, etc.)
    
    
    def openFile(self, MainWindow):
        print("Open functionality is initialized")
        self.result_display_label.setText("Open functionality is not implemented yet.")
    
    
    def generate_report(self, MainWindow):
        print("Generate Report functionality is initialized")
        self.result_display_label.setText("Generate Report functionality is not implemented yet.")
        
        
    def open_documentation(self):
        print("Documentation functionality is initialized")
        self.result_display_label.setText("Documentation functionality is not implemented yet.")
        """Displays application documentation."""
        print("Action: Documentation")
   
    
    def open_whats_new(self, MainWindow):
        print("What's New functionality is initialized")
        self.result_display_label.setText("What's New functionality is not implemented yet.")
            


    def displayLateralResults(self, result):

        self.AOD_lineEdit.setText(f"{result['Area_of_pipe_AOD']:.3f}")
        self.VOD_lineEdit.setText(f"{result['Volume_of_pipe_VOD']:.3f}")
        self.AID_lineEdit.setText(f"{result['Internal_Area_of_pipe_AID']:.3f}")
        self.VID_lineEdit.setText(f"{result['Volume_of_pipe_VID']:.3f}")
        self.At_lineEdit.setText(f"{result['Area_of_Thickness_At']:.3f}")
        self.Vt_lineEdit.setText(f"{result['Volume_of_Thickness_Vt']:.3f}")
        self.Mpipe_lineEdit.setText(f"{result['Mass_of_HDPE_pipe_Mpipe']:.3f}")
        self.Msea_water_lineEdit.setText(f"{result['Content_mass_inside_pipe_Mseawater']:.3f}")
        self.Bpipe_lineEdit.setText(f"{result['Buoyancy_for_pipe_Bpipe']:.3f}")
        self.Mc_lineEdit.setText(f"{result['Mass_of_concrete_Mc']:.3f}")
        self.Bc_lineEdit.setText(f"{result['Buoyancy_for_concrete_Bc']:.3f}")
        self.Wp_lineEdit.setText(f"{result['Submerged_Wt_of_pipe_Wp']:.3f}")
        self.Wc_lineEdit.setText(f"{result['Submerged_Wt_of_concrete_Wc']:.3f}")
        self.Ws_lineEdit.setText(f"{result['Total_Submerged_Wt_pipe_concrete_waterfilled_Ws1']:.3f}")
        self.Criteria1_lineEdit.setText(f"{result['gamma_SC1']:.3f}")
        self.Criteria2_lineEdit.setText(f"{result['gamma_SC2']:.3f}")

        self.result_display_label.setText(
            str(result['LSC_min']) + str(result['LSC_min1'])
        )


    def displayVerticalResults(self, result):

        self.AOD_lineEdit.setText(f"{result['A_OD']:.3f}")
        self.VOD_lineEdit.setText(f"{result['V_OD']:.3f}")
        self.AID_lineEdit.setText(f"{result['A_ID']:.3f}")
        self.VID_lineEdit.setText(f"{result['V_ID']:.3f}")
        self.At_lineEdit.setText(f"{result['A_t']:.3f}")
        self.Vt_lineEdit.setText(f"{result['V_t']:.3f}")
        self.Mpipe_lineEdit.setText(f"{result['M_pipe']:.3f}")
        self.Msea_water_lineEdit.setText(f"{result['M_seawater']:.3f}")
        self.Bpipe_lineEdit.setText(f"{result['B_pipe']:.3f}")
        self.Mc_lineEdit.setText(f"{result['M_c']:.3f}")
        self.Bc_lineEdit.setText(f"{result['B_c']:.3f}")
        self.Wp_lineEdit.setText(f"{result['W_p']:.3f}")
        self.Wc_lineEdit.setText(f"{result['W_c']:.3f}")
        self.Ws_lineEdit.setText(f"{result['W_s']:.3f}")
        self.SG_lineEdit.setText(f"{result['SG']:.3f}")
        self.Criteria1_lineEdit.setText(f"{result['UC']:.3f}")
        self.result_display_label.setText(str(result['UC_status']))
        
    


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "On Bottom Stability"))
        self.label_select1.setText(_translate("MainWindow", "On-Bottom Stability :  "))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Lateral Stability"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "Vertical Stability"))
        self.label_ProjectName.setText(_translate("MainWindow", "Project Name:"))
        self.label_DocNo.setText(_translate("MainWindow", "Doc No. :"))
        self.label_selectCase.setText(_translate("MainWindow", "Select Case :"))
        self.combobox_selectCase.setItemText(0, _translate("MainWindow", "Select the stability"))
        # self.combobox_selectCase.setItemText(1, _translate("MainWindow", "Operation"))
        self.label_PipeGrade.setText(_translate("MainWindow", "Pipeline Grade:"))
        self.comboBox_pipeGrade.setItemText(0, _translate("MainWindow", "API 5L X52"))
        self.comboBox_pipeGrade.setItemText(1, _translate("MainWindow", "API 5L X60"))
        self.comboBox_pipeGrade.setItemText(2, _translate("MainWindow", "API 5L X65"))
        self.comboBox_pipeGrade.setItemText(3, _translate("MainWindow", "API 5L X70"))
        self.comboBox_pipeGrade.setItemText(4, _translate("MainWindow", "API 5L X80"))
        self.result_display_label.setText(_translate("MainWindow", "-"))
        self.Criteria1_label.setText(_translate("MainWindow", " Criteria1  "))
        self.Criteria2_label.setText(_translate("MainWindow", " Criteria 2 "))
        self.pushButton_check.setText(_translate("MainWindow", "Check"))
        # self.checks_label.setText(_translate("MainWindow", "Checks"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.Hs_label.setText(_translate("MainWindow", "Significant Wave Height Hs (m)  "))
        self.Tp_label.setText(_translate("MainWindow", "Spectral Peak Period Tp (s)  "))
        self.d_label.setText(_translate("MainWindow", "Water Depth d  (m)  "))
        self.related_angle_theta_label.setText(_translate("MainWindow", "Related angle b/w pipeline & current direction θ (°)  "))
        self.zr_label.setText(_translate("MainWindow", "Ref. measure height above the seabed zr (m)  "))
        self.ys_label.setText(_translate("MainWindow", "Submerged unit Soil Weight for Sand γs (kN/m3)  "))
        self.mg_thickness_label.setText(_translate("MainWindow", "Marine Growth Thickness tmg (mm)  "))
        self.rho_cont_label.setText(_translate("MainWindow", "Content Density ρcont (kg/m3)"))
        self.rho_c_label.setText(_translate("MainWindow", "Concrete Density ρc (kg/m3)"))
        self.yw_label.setText(_translate("MainWindow", "Safety Factor for Weight γw "))
        self.mg_density_label.setText(_translate("MainWindow", "Marine Growth Density ρmg (mm)  "))
        self.rho_HDPE_label.setText(_translate("MainWindow", "HDPE Density ρHDPE (kg/m3)"))
        self.OD_label.setText(_translate("MainWindow", "Outside  Diameter OD (mm)"))
        self.tHDPE_label.setText(_translate("MainWindow", "Wall Thickness tHDPE (mm)"))
        self.concrete_coating_thickness_label.setText(_translate("MainWindow", "Concrete Coating Thickness tcc (m) "))
        self.CA_label.setText(_translate("MainWindow", "Corrosion Allowance CA (m)"))
        self.Vc_label.setText(_translate("MainWindow", "Volume of Concrete Vc (m3)"))
        # self.label_INPUT_Data.setText(_translate("MainWindow", "Input Data"))
        self.VID_label_54.setText(_translate("MainWindow", "Volume of pipe (VID) (m3)"))
        self.AID_label.setText(_translate("MainWindow", "Internal area of pipe(AID) (m2)"))
        self.VOD_label.setText(_translate("MainWindow", "Volume of pipe (VOD) (m3)"))
        self.At_label.setText(_translate("MainWindow", "Area of Thickness (At) (m2)"))
        self.AOD_label.setText(_translate("MainWindow", "Area of pipe (AOD) (m2)"))
        self.Vt_label.setText(_translate("MainWindow", "Volume of Thickness (Vt) (m3)"))
        self.Msea_water_label.setText(_translate("MainWindow", "Content mass inside pipe (Msea_water) (kg/m)"))
        self.M_pipe_label.setText(_translate("MainWindow", "Mass of HDPE pipe (Mpipe) (kg/m)"))
        self.Bpipe_label.setText(_translate("MainWindow", "Bouyancy for pipe (Bpipe) (kg/m)"))
        self.Mc_label.setText(_translate("MainWindow", "Mass of Concrete (Mc) (kg/m)"))
        self.Wp_label.setText(_translate("MainWindow", "Submerged Wt of pipe (Wp) (kg/m)"))
        self.Bc_label.setText(_translate("MainWindow", "Buoyancy for Concrete (Bc) (kg/m)"))
        self.Wc_label.setText(_translate("MainWindow", "Submerged Wt. of Concrete (Wc) (kg/m)"))
        self.SG_label.setText(_translate("MainWindow", "Specific Gravity (SG)                                       "))
        self.Ws_label.setText(_translate("MainWindow", "Total submerged  Wt (pipe + concrete) (Ws) (kg/m)"))
        # self.Label_Result.setText(_translate("MainWindow", " Result Terminal"))
        self.label_copyright.setText(_translate("MainWindow", "© 2026 Ashkam Energy Pvt. Ltd. All rights reserved."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Shift+R"))
        self.actionGenerate_Report.setText(_translate("MainWindow", "Generate Report"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionWhat_s_New.setText(_translate("MainWindow", "What\'s New"))


    def EnableResultLabel(self):
        self.result_display_label.show()


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())




# -----------------------------------
# Wrapper Class (REAL Window)
# -----------------------------------
class PipelineOnBottomStability(QMainWindow):
    def __init__(self):
        super().__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)