# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FreeSpan_update1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from datetime import datetime
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import math

from calculations import freeSpan_Analysis_calculation

# from utils import save_inputs, load_inputs_mapped, generate_report, open_screen
# from utils import caseOption, get_all_inputs, get_required_inputs, DocumentationScreen, WhatsNewScreen, open_screen
# from utils import generate_report
# from utils import save_inputs, load_inputs_mapped, generate_report, open_screen
from utils import caseOption, get_all_inputs, get_required_inputs, DocumentationScreen, WhatsNewScreen, save_inputs, load_inputs_mapped, generate_report, ResultSummary, open_screen
from utils import caseOption, get_all_inputs, get_required_inputs, DocumentationScreenFreeSpan, WhatsNewScreenFreeSpan, save_inputs, load_inputs_mapped, generate_report, open_screen
from utils import generate_report, constant, Content_Type_For_Installation, PIPE_GRADES, BOUNDARY_CONDITIONS, Deflection_Criteria, Boundary_Library


__version__ = "0.0.1"
print(f"Loading On Free Span Analysis module version {__version__}...")


class SNGraphCanvas(FigureCanvas):
    def __init__(self, parent=None):
        self.figure = Figure(figsize=(5, 3))  # 👈 controls proportion
        self.ax = self.figure.add_subplot(111)
        super().__init__(self.figure)

        # Allow resizing
        self.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Expanding
        )



class Ui_MainWindow(object):

    # ----module name for report generation------

    Module_Name = "Free Span Analysis"

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 716)
        # MainWindow.resize(1065, 716)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../SPIS/assets/OnBottomRoughness.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.028, y1:0.0455909, x2:0.841, y2:0.966364, stop:0 rgba(169, 237, 255, 107), stop:0.994318 rgba(253, 255, 218, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.INPUT_DATA = QtWidgets.QGroupBox(self.groupBox_2)
        self.INPUT_DATA.setObjectName("INPUT_DATA")
        self.gridLayout = QtWidgets.QGridLayout(self.INPUT_DATA)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(27, 43, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.Pipe_geometry = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pipe_geometry.setFont(font)
        self.Pipe_geometry.setObjectName("Pipe_geometry")
        self.gridLayout.addWidget(self.Pipe_geometry, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 111, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 10, 3, 1)
        self.Environment = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Environment.setFont(font)
        self.Environment.setObjectName("Environment")
        self.gridLayout.addWidget(self.Environment, 7, 5, 1, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Wall_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Wall_thickness_label.setObjectName("Wall_thickness_label")
        self.horizontalLayout_4.addWidget(self.Wall_thickness_label)
        self.Wall_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Wall_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Wall_thickness_lineEdit.setObjectName("Wall_thickness_lineEdit")
        self.horizontalLayout_4.addWidget(self.Wall_thickness_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Coating_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Coating_thickness_label.setObjectName("Coating_thickness_label")
        self.horizontalLayout_3.addWidget(self.Coating_thickness_label)
        self.Coating_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Coating_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Coating_thickness_lineEdit.setObjectName("Coating_thickness_lineEdit")
        self.horizontalLayout_3.addWidget(self.Coating_thickness_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Concrete_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Concrete_thickness_label.setObjectName("Concrete_thickness_label")
        self.horizontalLayout_2.addWidget(self.Concrete_thickness_label)
        self.Concrete_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Concrete_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Concrete_thickness_lineEdit.setObjectName("Concrete_thickness_lineEdit")
        self.horizontalLayout_2.addWidget(self.Concrete_thickness_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Internal_pressure_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Internal_pressure_label.setObjectName("Internal_pressure_label")
        self.horizontalLayout_10.addWidget(self.Internal_pressure_label)
        self.Internal_pressure_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Internal_pressure_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Internal_pressure_lineEdit.setObjectName("Internal_pressure_lineEdit")
        self.horizontalLayout_10.addWidget(self.Internal_pressure_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_3, 8, 0, 2, 4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 8, 4, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()  
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Current_Velocity_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Current_Velocity_label.setObjectName("Current_Velocity_label")
        self.horizontalLayout_6.addWidget(self.Current_Velocity_label)
        self.Current_Velocity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Current_Velocity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Current_Velocity_lineEdit.setObjectName("Current_Velocity_lineEdit")
        self.horizontalLayout_6.addWidget(self.Current_Velocity_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Wave_velocity_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Wave_velocity_label.setObjectName("Wave_velocity_label")
        self.horizontalLayout_7.addWidget(self.Wave_velocity_label)
        self.Wave_velocity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Wave_velocity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Wave_velocity_lineEdit.setObjectName("Wave_velocity_lineEdit")
        self.horizontalLayout_7.addWidget(self.Wave_velocity_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout_2, 8, 5, 1, 5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Span_Length_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Span_Length_label.setObjectName("Span_Length_label")
        self.horizontalLayout_17.addWidget(self.Span_Length_label)
        self.Span_Length_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Span_Length_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Span_Length_lineEdit.setObjectName("Span_Length_lineEdit")
        self.horizontalLayout_17.addWidget(self.Span_Length_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Outer_Diameter_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Outer_Diameter_label.setObjectName("Outer_Diameter_label")
        self.horizontalLayout_5.addWidget(self.Outer_Diameter_label)
        self.Outer_diameter_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Outer_diameter_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Outer_diameter_lineEdit.setObjectName("Outer_diameter_lineEdit")
        self.horizontalLayout_5.addWidget(self.Outer_diameter_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 2, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 7, 1, 1)
        self.Expansion_condition_Constant = QtWidgets.QComboBox(self.INPUT_DATA)
        self.Expansion_condition_Constant.setStyleSheet("")
        self.Expansion_condition_Constant.setEditable(True)
        self.Expansion_condition_Constant.setObjectName("Expansion_condition_Constant")
        self.Expansion_condition_Constant.addItem("")
        self.Expansion_condition_Constant.addItem("")
        self.Expansion_condition_Constant.addItem("")
        self.Expansion_condition_Constant.addItem("")
        self.gridLayout.addWidget(self.Expansion_condition_Constant, 1, 8, 1, 3)
        self.Material_Property = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Material_Property.setFont(font)
        self.Material_Property.setObjectName("Material_Property")
        self.gridLayout.addWidget(self.Material_Property, 3, 5, 1, 3)
        self.Boundary_condition_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        self.Boundary_condition_comboBox.setStyleSheet("")
        self.Boundary_condition_comboBox.setEditable(True)
        self.Boundary_condition_comboBox.setObjectName("Boundary_condition_comboBox")
        self.Boundary_condition_comboBox.addItem("")
        self.Boundary_condition_comboBox.addItem("")
        self.Boundary_condition_comboBox.addItem("")
        self.Boundary_condition_comboBox.addItem("")
        self.gridLayout.addWidget(self.Boundary_condition_comboBox, 0, 1, 1, 2)
        self.L_by_D_check = QtWidgets.QLabel(self.INPUT_DATA)
        self.L_by_D_check.setObjectName("L_by_D_check")
        self.gridLayout.addWidget(self.L_by_D_check, 2, 4, 1, 1)
        self.Pipeline_Grade_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        self.Pipeline_Grade_comboBox.setStyleSheet("")
        self.Pipeline_Grade_comboBox.setEditable(True)
        self.Pipeline_Grade_comboBox.setObjectName("Pipeline_Grade_comboBox")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.gridLayout.addWidget(self.Pipeline_Grade_comboBox, 0, 0, 1, 1)
        self.Material_Property_2 = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.Material_Property_2.setFont(font)
        self.Material_Property_2.setObjectName("Material_Property_2")
        self.gridLayout.addWidget(self.Material_Property_2, 4, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Operational_temperature_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Operational_temperature_label.setObjectName("Operational_temperature_label")
        self.horizontalLayout_8.addWidget(self.Operational_temperature_label)
        self.Operational_temparature_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Operational_temparature_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Operational_temparature_lineEdit.setObjectName("Operational_temparature_lineEdit")
        self.horizontalLayout_8.addWidget(self.Operational_temparature_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Installation_temperature_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Installation_temperature_label.setObjectName("Installation_temperature_label")
        self.horizontalLayout_9.addWidget(self.Installation_temperature_label)
        self.Installation_temperature_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Installation_temperature_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Installation_temperature_lineEdit.setObjectName("Installation_temperature_lineEdit")
        self.horizontalLayout_9.addWidget(self.Installation_temperature_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_4, 5, 0, 2, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Coating_density_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Coating_density_label.setObjectName("Coating_density_label")
        self.horizontalLayout.addWidget(self.Coating_density_label)
        self.Coating_Dessity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Coating_Dessity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Coating_Dessity_lineEdit.setObjectName("Coating_Dessity_lineEdit")
        self.horizontalLayout.addWidget(self.Coating_Dessity_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 5, 1, 5)
        self.select_test_case_combobox = QtWidgets.QComboBox(self.INPUT_DATA)
        self.select_test_case_combobox.setStyleSheet("")
        self.select_test_case_combobox.setEditable(True)
        self.select_test_case_combobox.setObjectName("select_test_case_combobox")
        self.select_test_case_combobox.addItem("")
        self.select_test_case_combobox.addItem("")
        self.select_test_case_combobox.addItem("")
        self.select_test_case_combobox.addItem("")
        self.gridLayout.addWidget(self.select_test_case_combobox, 0, 3, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(139, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 9, 4, 1, 3)
        self.Run_pushButton = QtWidgets.QPushButton(self.INPUT_DATA)
        self.Run_pushButton.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.Run_pushButton.setObjectName("Run_pushButton")
        self.gridLayout.addWidget(self.Run_pushButton, 9, 8, 1, 2)
        self.Content_Type_case_Combobox = QtWidgets.QComboBox(self.INPUT_DATA)
        self.Content_Type_case_Combobox.setStyleSheet("")
        self.Content_Type_case_Combobox.setEditable(True)
        self.Content_Type_case_Combobox.setObjectName("Content_Type_case_Combobox")
        self.Content_Type_case_Combobox.addItem("")
        self.Content_Type_case_Combobox.addItem("")
        self.Content_Type_case_Combobox.addItem("")
        self.Content_Type_case_Combobox.addItem("")
        self.Content_Type_case_Combobox.addItem("")
        self.Content_Type_case_Combobox.addItem("")
        self.gridLayout.addWidget(self.Content_Type_case_Combobox, 0, 5, 1, 3)
        self.Deflection_factor_Combobox = QtWidgets.QComboBox(self.INPUT_DATA)
        self.Deflection_factor_Combobox.setStyleSheet("")
        self.Deflection_factor_Combobox.setEditable(True)
        self.Deflection_factor_Combobox.setObjectName("Deflection_factor_Combobox")
        self.Deflection_factor_Combobox.addItem("")
        self.Deflection_factor_Combobox.addItem("")
        self.Deflection_factor_Combobox.addItem("")
        self.Deflection_factor_Combobox.addItem("")
        self.Deflection_factor_Combobox.addItem("")
        self.Deflection_factor_Combobox.addItem("")
        self.gridLayout.addWidget(self.Deflection_factor_Combobox, 0, 8, 1, 3)
        self.gridLayout_4.addWidget(self.INPUT_DATA, 0, 0, 3, 1)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.Project_label = QtWidgets.QLabel(self.groupBox_2)
        self.Project_label.setObjectName("Project_label")
        self.horizontalLayout_38.addWidget(self.Project_label)
        self.Project_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.Project_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Project_lineEdit.setObjectName("Project_lineEdit")
        self.horizontalLayout_38.addWidget(self.Project_lineEdit)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.Project_code_label = QtWidgets.QLabel(self.groupBox_2)
        self.Project_code_label.setObjectName("Project_code_label")
        self.horizontalLayout_37.addWidget(self.Project_code_label)
        self.Project_Code_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.Project_Code_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Project_Code_lineEdit.setObjectName("Project_Code_lineEdit")
        self.horizontalLayout_37.addWidget(self.Project_Code_lineEdit)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_37)
        self.gridLayout_4.addLayout(self.horizontalLayout_39, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(336, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 1, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 2, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 999, 193))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RESULT_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RESULT_label.setFont(font)
        self.RESULT_label.setObjectName("RESULT_label")
        self.gridLayout_2.addWidget(self.RESULT_label, 0, 0, 1, 1)
        self.Result_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Result_textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Result_textEdit.setObjectName("Result_textEdit")
        self.gridLayout_2.addWidget(self.Result_textEdit, 1, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(829, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 3, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(451, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 1, 1, 1)
        self.ShowMore_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.ShowMore_pushButton.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.ShowMore_pushButton.setObjectName("ShowMore_pushButton")
        self.gridLayout_3.addWidget(self.ShowMore_pushButton, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 626, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 0, 2, 1, 1)
        self.copyright_label = QtWidgets.QLabel(self.centralwidget)
        self.copyright_label.setObjectName("copyright_label")
        self.gridLayout_5.addWidget(self.copyright_label, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(950, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 1, 1, 2, 1)

        
        # self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        # self.gridLayout.setObjectName("gridLayout")
        # self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        # self.groupBox_2.setTitle("")
        # self.groupBox_2.setObjectName("groupBox_2")
        # self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        # self.gridLayout_5.setObjectName("gridLayout_5")
        # self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        # self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        # self.Project_label = QtWidgets.QLabel(self.groupBox_2)
        # self.Project_label.setObjectName("Project_label")
        # self.horizontalLayout_38.addWidget(self.Project_label)
        # self.Project_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        # self.Project_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Project_lineEdit.setObjectName("Project_lineEdit")
        # self.horizontalLayout_38.addWidget(self.Project_lineEdit)
        # self.horizontalLayout_39.addLayout(self.horizontalLayout_38)
        # self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        # self.Project_code_label = QtWidgets.QLabel(self.groupBox_2)
        # self.Project_code_label.setObjectName("Project_code_label")
        # self.horizontalLayout_37.addWidget(self.Project_code_label)
        # self.Project_Code_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        # self.Project_Code_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Project_Code_lineEdit.setObjectName("Project_Code_lineEdit")
        # self.horizontalLayout_37.addWidget(self.Project_Code_lineEdit)
        # self.horizontalLayout_39.addLayout(self.horizontalLayout_37)
        # self.gridLayout_5.addLayout(self.horizontalLayout_39, 0, 1, 1, 1)
        # self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        # self.scrollArea.setWidgetResizable(True)
        # self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 932, 231))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.label_SteelArea = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.label_SteelArea.setGeometry(10, 10, 300, 30)  # adjust as needed
        # self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        # self.gridLayout_2.setObjectName("gridLayout_2")
        # self.RESULT_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # font.setBold(True)
        # font.setWeight(75)
        # self.RESULT_label.setFont(font)
        # self.RESULT_label.setObjectName("RESULT_label")
        # self.gridLayout_2.addWidget(self.RESULT_label, 0, 0, 1, 1)
        # self.Result_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        # self.Result_textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Result_textEdit.setObjectName("Result_textEdit")
        # self.Result_textEdit.setReadOnly(True)  # Make it read-only
        # self.gridLayout_2.addWidget(self.Result_textEdit, 1, 0, 1, 2)
        # spacerItem = QtWidgets.QSpacerItem(829, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        # self.gridLayout_5.addWidget(self.scrollArea, 3, 0, 1, 2)

        # self.sn_canvas = SNGraphCanvas(self.groupBox_2)
        # self.sn_canvas.setStyleSheet("background-color: white;")
        # self.gridLayout_5.addWidget(self.sn_canvas, 2, 1, 1, 1, QtCore.Qt.AlignTop)
        # # Balance layout properly
        # self.gridLayout_5.setColumnStretch(0, 1)
        # self.gridLayout_5.setColumnStretch(1, 1)

        # self.gridLayout_5.setRowStretch(0, 0)
        # self.gridLayout_5.setRowStretch(1, 0)
        # self.gridLayout_5.setRowStretch(2, 1)  # 👈 graph row
        # self.gridLayout_5.setRowStretch(3, 1)


        # # self.graphicsView.setStyleSheet("background-color: rgb(255, 255, 255);")
        # # self.graphicsView.setObjectName("graphicsView")
        # # self.gridLayout_5.addWidget(self.graphicsView, 2, 1, 1, 1)
        # spacerItem1 = QtWidgets.QSpacerItem(336, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout_5.addItem(spacerItem1, 1, 1, 1, 1)
        # self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        # self.groupBox_4.setTitle("")
        # self.groupBox_4.setObjectName("groupBox_4")
        # self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        # self.gridLayout_3.setObjectName("gridLayout_3")
        # spacerItem2 = QtWidgets.QSpacerItem(451, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout_3.addItem(spacerItem2, 1, 1, 1, 1)
        # self.ShowMore_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        # self.ShowMore_pushButton.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        # self.ShowMore_pushButton.setObjectName("ShowMore_pushButton")
        # self.gridLayout_3.addWidget(self.ShowMore_pushButton, 1, 0, 1, 1)
        # self.gridLayout_5.addWidget(self.groupBox_4, 4, 0, 1, 2)
        # self.INPUT_DATA = QtWidgets.QGroupBox(self.groupBox_2)
        # self.INPUT_DATA.setObjectName("INPUT_DATA")
        # self.gridLayout_4 = QtWidgets.QGridLayout(self.INPUT_DATA)
        # self.gridLayout_4.setObjectName("gridLayout_4")
        # spacerItem3 = QtWidgets.QSpacerItem(115, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.gridLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        # self.verticalLayout = QtWidgets.QVBoxLayout()
        # self.verticalLayout.setObjectName("verticalLayout")
        # self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        # self.Span_Length_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Span_Length_label.setObjectName("Span_Length_label")
        # self.horizontalLayout_17.addWidget(self.Span_Length_label)
        # self.Span_Length_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Span_Length_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Span_Length_lineEdit.setObjectName("Span_Length_lineEdit")
        # self.horizontalLayout_17.addWidget(self.Span_Length_lineEdit)
        # self.verticalLayout.addLayout(self.horizontalLayout_17)
        # self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        # self.Outer_Diameter_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Outer_Diameter_label.setObjectName("Outer_Diameter_label")
        # self.horizontalLayout_5.addWidget(self.Outer_Diameter_label)
        # self.Outer_diameter_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Outer_diameter_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Outer_diameter_lineEdit.setObjectName("Outer_diameter_lineEdit")
        # self.horizontalLayout_5.addWidget(self.Outer_diameter_lineEdit)
        # self.verticalLayout.addLayout(self.horizontalLayout_5)
        # self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 2)
        # self.L_by_D_check = QtWidgets.QLabel(self.INPUT_DATA)
        # self.L_by_D_check.setObjectName("L_by_D_check")
        # self.gridLayout_4.addWidget(self.L_by_D_check, 1, 3, 1, 1)
        # spacerItem4 = QtWidgets.QSpacerItem(69, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.gridLayout_4.addItem(spacerItem4, 1, 5, 1, 1)
        # self.Material_Property_2 = QtWidgets.QLabel(self.INPUT_DATA)
        # font = QtGui.QFont()
        # font.setPointSize(6)
        # font.setBold(False)
        # font.setWeight(50)
        # self.Material_Property_2.setFont(font)
        # self.Material_Property_2.setObjectName("Material_Property_2")
        # self.gridLayout_4.addWidget(self.Material_Property_2, 2, 0, 1, 1)
        # self.Material_Property = QtWidgets.QLabel(self.INPUT_DATA)
        # font = QtGui.QFont()
        # font.setBold(True)
        # font.setWeight(75)
        # self.Material_Property.setFont(font)
        # self.Material_Property.setObjectName("Material_Property")
        # self.gridLayout_4.addWidget(self.Material_Property, 2, 3, 1, 2)
        # self.horizontalLayout = QtWidgets.QHBoxLayout()
        # self.horizontalLayout.setObjectName("horizontalLayout")
        # self.Coating_density_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Coating_density_label.setObjectName("Coating_density_label")
        # self.horizontalLayout.addWidget(self.Coating_density_label)
        # self.Coating_Dessity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Coating_Dessity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Coating_Dessity_lineEdit.setObjectName("Coating_Dessity_lineEdit")
        # self.horizontalLayout.addWidget(self.Coating_Dessity_lineEdit)
        # self.gridLayout_4.addLayout(self.horizontalLayout, 3, 3, 1, 3)
        # self.Pipe_geometry = QtWidgets.QLabel(self.INPUT_DATA)
        # font = QtGui.QFont()
        # font.setBold(True)
        # font.setWeight(75)
        # self.Pipe_geometry.setFont(font)
        # self.Pipe_geometry.setObjectName("Pipe_geometry")
        # self.gridLayout_4.addWidget(self.Pipe_geometry, 4, 0, 1, 1)
        # spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.gridLayout_4.addItem(spacerItem5, 4, 3, 2, 1)
        # self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        # self.verticalLayout_3.setObjectName("verticalLayout_3")
        # self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        # self.Wall_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Wall_thickness_label.setObjectName("Wall_thickness_label")
        # self.horizontalLayout_4.addWidget(self.Wall_thickness_label)
        # self.Wall_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Wall_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Wall_thickness_lineEdit.setObjectName("Wall_thickness_lineEdit")
        # self.horizontalLayout_4.addWidget(self.Wall_thickness_lineEdit)
        # self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        # self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        # self.Coating_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Coating_thickness_label.setObjectName("Coating_thickness_label")
        # self.horizontalLayout_3.addWidget(self.Coating_thickness_label)
        # self.Coating_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Coating_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Coating_thickness_lineEdit.setObjectName("Coating_thickness_lineEdit")
        # self.horizontalLayout_3.addWidget(self.Coating_thickness_lineEdit)
        # self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        # self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.Concrete_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Concrete_thickness_label.setObjectName("Concrete_thickness_label")
        # self.horizontalLayout_2.addWidget(self.Concrete_thickness_label)
        # self.Concrete_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Concrete_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Concrete_thickness_lineEdit.setObjectName("Concrete_thickness_lineEdit")
        # self.horizontalLayout_2.addWidget(self.Concrete_thickness_lineEdit)
        # self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        # self.gridLayout_4.addLayout(self.verticalLayout_3, 5, 0, 3, 2)
        # spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout_4.addItem(spacerItem6, 6, 2, 1, 1)
        # self.Environment = QtWidgets.QLabel(self.INPUT_DATA)
        # font = QtGui.QFont()
        # font.setBold(True)
        # font.setWeight(75)
        # self.Environment.setFont(font)
        # self.Environment.setObjectName("Environment")
        # self.gridLayout_4.addWidget(self.Environment, 6, 3, 1, 1)
        # self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        # self.verticalLayout_2.setObjectName("verticalLayout_2")
        # self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        # self.Current_Velocity_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Current_Velocity_label.setObjectName("Current_Velocity_label")
        # self.horizontalLayout_6.addWidget(self.Current_Velocity_label)
        # self.Current_Velocity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Current_Velocity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Current_Velocity_lineEdit.setObjectName("Current_Velocity_lineEdit")
        # self.horizontalLayout_6.addWidget(self.Current_Velocity_lineEdit)
        # self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        # self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        # self.Wave_velocity_label = QtWidgets.QLabel(self.INPUT_DATA)
        # self.Wave_velocity_label.setObjectName("Wave_velocity_label")
        # self.horizontalLayout_7.addWidget(self.Wave_velocity_label)
        # self.Wave_velocity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        # self.Wave_velocity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.Wave_velocity_lineEdit.setObjectName("Wave_velocity_lineEdit")
        # self.horizontalLayout_7.addWidget(self.Wave_velocity_lineEdit)
        # self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        # self.gridLayout_4.addLayout(self.verticalLayout_2, 7, 3, 1, 3)
        # spacerItem7 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.gridLayout_4.addItem(spacerItem7, 7, 6, 1, 1)
        # spacerItem8 = QtWidgets.QSpacerItem(139, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout_4.addItem(spacerItem8, 8, 4, 1, 2)
        # self.Run_pushButton = QtWidgets.QPushButton(self.INPUT_DATA)
        # self.Run_pushButton.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        # self.Run_pushButton.setObjectName("Run_pushButton")
        # self.gridLayout_4.addWidget(self.Run_pushButton, 8, 6, 1, 1)
        # self.Pipeline_Grade_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        # self.Pipeline_Grade_comboBox.setStyleSheet("")
        # self.Pipeline_Grade_comboBox.setObjectName("Pipeline_Grade_comboBox")
        # self.Pipeline_Grade_comboBox.addItem("Select Pipeline Grade")
        # self.Pipeline_Grade_comboBox.addItems(PIPE_GRADES.keys())
        # self.gridLayout_4.addWidget(self.Pipeline_Grade_comboBox, 0, 3, 1, 2)
        # self.Boundary_condition_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        # self.Boundary_condition_comboBox.setStyleSheet("")
        # self.Boundary_condition_comboBox.setObjectName("Boundary_condition_comboBox")
        # self.Boundary_condition_comboBox.addItem("Select Boundary Condition")
        # self.Boundary_condition_comboBox.addItems(Boundary_Library.keys())
        # self.gridLayout_4.addWidget(self.Boundary_condition_comboBox, 0, 5, 1, 2)
        




        # self.Test_case_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        # self.Test_case_comboBox.setObjectName("Test_case_comboBox")
        # self.Test_case_comboBox.setStyleSheet("")

        # # Default item
        # self.Test_case_comboBox.addItem("Select Test Case")

        # # Add options
        # self.Test_case_comboBox.addItems([
        #     "Installation",
        #     "Hydrotest",
        #     "Operational",
        # ])

        # # Add to grid layout
        # self.gridLayout_4.addWidget(self.Test_case_comboBox, 0, 7, 1, 2)
        
        
        # self.Content_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        # self.Content_comboBox.setObjectName("Content_comboBox")
        # self.Content_comboBox.setStyleSheet("")

        # # Default item
        # self.Content_comboBox.addItem("Select Content Type")

        # # Add options
        # self.Content_comboBox.addItems(Content_Type_For_Installation.keys())
        
        # # Disable content combo box initially, will be enabled based on test case selection
        self.Content_Type_case_Combobox.setEnabled(False)

        # # Add to grid layout
        # self.gridLayout_4.addWidget(self.Content_comboBox, 0, 9, 1, 2)
        
        # self.Deflection_factor_Combobox = QtWidgets.QComboBox(self.INPUT_DATA)
        # self.Deflection_factor_Combobox.setObjectName("Deflection_factor_Combobox")

        # self.Deflection_factor_Combobox.addItem("Select Deflection Factor")
        # self.Deflection_factor_Combobox.addItems(Deflection_Criteria.keys())

        # self.gridLayout_4.addWidget(self.Deflection_factor_Combobox, 0, 11, 1, 2)
        
        
        # self.gridLayout_5.addWidget(self.INPUT_DATA, 0, 0, 3, 1)
        # self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 2)
        # spacerItem9 = QtWidgets.QSpacerItem(20, 626, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.gridLayout.addItem(spacerItem9, 0, 2, 1, 1)
        # self.copyright_label = QtWidgets.QLabel(self.centralwidget)
        # self.copyright_label.setObjectName("copyright_label")
        # self.gridLayout.addWidget(self.copyright_label, 1, 0, 1, 1)
        # spacerItem10 = QtWidgets.QSpacerItem(950, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout.addItem(spacerItem10, 1, 1, 1, 1)






        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 21))
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/new.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:/SPIS/assets/open.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        # self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:/SPIS/assets/save_as.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName("actionSave_As")
        # self.actionSave_As = QtWidgets.QAction(MainWindow)
        # self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("E:/SPIS/assets/close.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("E:/SPIS/assets/reset.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset.setIcon(icon5)
        self.actionReset.setObjectName("actionReset")
        self.actionWhat_s_New = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("E:/SPIS/assets/What\'s new.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWhat_s_New.setIcon(icon6)
        self.actionWhat_s_New.setObjectName("actionWhat_s_New")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("E:/SPIS/assets/report.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentation.setIcon(icon7)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionGenerate_Report = QtWidgets.QAction(MainWindow)
        self.actionGenerate_Report.setIcon(icon7)
        self.actionGenerate_Report.setObjectName("actionGenerate_Report")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionReset)
        self.menuReport.addAction(self.actionGenerate_Report)
        self.menuHelp.addAction(self.actionWhat_s_New)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.ShowMore_pushButton.setDisabled(True)


        self.input_fields = {
           "Project Name" : self.Project_lineEdit,
           "Document Number": self.Project_Code_lineEdit,
           "Pipeline Grade": self.Pipeline_Grade_comboBox,
           "Boundary Condition": self.Boundary_condition_comboBox,
           "Span Length" : self.Span_Length_lineEdit,
           "Outer Diameter" : self.Outer_diameter_lineEdit,
           "Coating Density" : self.Coating_Dessity_lineEdit,
           "Wall Thickness" : self.Wall_thickness_lineEdit,
           "Coating Thickness" : self.Coating_thickness_lineEdit,
           "Concrete Thickness" : self.Concrete_thickness_lineEdit,
           "Current Velocity" : self.Current_Velocity_lineEdit,
           "Wave Velocity" : self.Wave_velocity_lineEdit,
           "Test Case" : self.select_test_case_combobox,
           "Content Type" : self.Content_Type_case_Combobox,
           "Deflection Factor" : self.Deflection_factor_Combobox,
           "Expansion Constant" : self.Expansion_condition_Constant,
           "Operatinal Temperature " : self.Operational_temparature_lineEdit,
           "Installation Temperature" : self.Installation_temperature_lineEdit,
           "Internal Pressure" : self.Internal_pressure_lineEdit,

        }

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Run_pushButton.clicked.connect(self.inputData)
        self.ShowMore_pushButton.clicked.connect(self.open_summary_result)



#--------------------------------------------------Functions are from here--------------------------------------------------------------

         # Menu bar functions
        self.actionReset.triggered.connect(self.reset_all)
        self.actionSave_As.triggered.connect(self.save_As)
        self.actionOpen.triggered.connect(self.openFile)
        self.actionGenerate_Report.triggered.connect(self.generate_report)
        self.actionDocumentation.triggered.connect(self.open_documentation)
        self.actionWhat_s_New.triggered.connect(self.open_whats_new)
        
        self.open_windows = []
        
        self.test_condition = None
        self.content_type = None
        self.deflection_criteria = None
        
        # Test case selection change function
        self.select_test_case_combobox.currentIndexChanged.connect(self.test_case_selection_changed)
        # Content type selection change function
        self.Content_Type_case_Combobox.currentIndexChanged.connect(self.content_selection_changed)
        # Deflection criteria selection change function
        self.Deflection_factor_Combobox.currentIndexChanged.connect(self.deflection_criteria_selection_changed)
        
        
    # --------------------------Functions for buttons and combo box changes------------------------------------   
    # Test case selection change function  
    def test_case_selection_changed(self):
        selected_test_case = self.select_test_case_combobox.currentText()
        self.test_condition = selected_test_case
        
        if selected_test_case == "Operational":
            self.Content_Type_case_Combobox.setEnabled(True)
            self.Content_Type_case_Combobox.clear()
            self.Content_Type_case_Combobox.addItem("Select Content Type")
            self.Content_Type_case_Combobox.addItems(Content_Type_For_Installation.keys())
            print("Operational test case selected. Content type combo box enabled.")
            print("Available content types: ", Content_Type_For_Installation.keys())
        else:
            self.Content_Type_case_Combobox.setEnabled(False)
            self.Content_Type_case_Combobox.clear()
            self.Content_Type_case_Combobox.addItem("Select Content Type")
            print(f"{selected_test_case} test case selected. Content type combo box disabled.")
            
    # Content selection change function
    def content_selection_changed(self):
        content_type = self.Content_Type_case_Combobox.currentText()
        self.content_type = content_type
        content_Density = Content_Type_For_Installation.get(content_type, None)
        print(f"Content type selected: {content_type}")
        print(f"Content density: {content_Density}")
      
        
    # Deflection criteria selection change function
    def deflection_criteria_selection_changed(self):
        selected_deflection_criteria = self.Deflection_factor_Combobox.currentText()
        self.deflection_criteria = Deflection_Criteria.get(selected_deflection_criteria, None)
        print(f"Deflection criteria selected: {selected_deflection_criteria}")
        



    # Function to input data and perform calculations when Run button is clicked
    def inputData(self):
        print("Input data function called")    
        
        try:

            selected_grade = self.Pipeline_Grade_comboBox.currentText()
            selected_test_case = self.select_test_case_combobox.currentText()
            self.test_condition = selected_test_case
            content_type = self.Content_Type_case_Combobox.currentText()
            self.content_type = content_type
            deflection_criteria_type = self.Deflection_factor_Combobox.currentText()
            
            # Check if deflection criteria is selected
            if deflection_criteria_type == "Select Deflection Factor":
                QtWidgets.QMessageBox.warning(
                    None,
                    "Input Error",
                    "Please select a valid deflection criteria before running the analysis."
                )
                return
            
            # Check if pipeline grade and test case are selected
            if selected_grade == "Select Pipe Grade" or selected_test_case == "Select Test Case":
                QtWidgets.QMessageBox.warning(
                    None,
                    "Input Error",
                    "Please select a valid pipe grade and test case before running the analysis."
                )
                return
            
            # Check if content type is selected for operational test case
            if selected_test_case == "Operational" and content_type == "Select Content Type":
                QtWidgets.QMessageBox.warning(
                    None,
                    "Input Error",
                    "Please select a valid content type for operational test case."
                )
                return
            
            yield_strength = PIPE_GRADES[selected_grade]
            test_case = self.select_test_case_combobox.currentText()
            content_density = Content_Type_For_Installation.get(content_type, None) if content_type != "Select Content Type" else None

            selected_boundaryCondition = self.Boundary_condition_comboBox.currentText()
            if selected_boundaryCondition == "Select Boundary Condition":
                QtWidgets.QMessageBox.warning(
                    None,
                    "Input Error",
                    "Please select a valid Boundary condition."
                )
                return
            
            # beta_value = BOUNDARY_CONDITIONS[selected_boundaryCondition]
            beta_value = 3.14  # Placeholder value, replace with actual lookup from BOUNDARY_CONDITIONS
            boundary_condition = self.Boundary_condition_comboBox.currentText()
            boundary = Boundary_Library.get(boundary_condition, {})
            beta = boundary.get("beta")
            deflection_factor = boundary.get("deflection_factor")
            moment_factor = boundary.get("moment_factor")
            # print(f"Selected boundary condition: {boundary_condition}")
            # print(f"Boundary condition parameters - Beta: {beta}, Deflection Factor: {deflection_factor}, Moment Factor: {moment_factor}")
            

            frontendData = {
                "Assumed_Span_Length" : float(self.Span_Length_lineEdit.text()),
                "Outer_Diameter" : float(self.Outer_diameter_lineEdit.text()),
                "Coating_Density" : float(self.Coating_Dessity_lineEdit.text()),
                "Wall_Thickness" : float(self.Wall_thickness_lineEdit.text()),
                "Coating_Thickness" : float(self.Coating_thickness_lineEdit.text()),
                "Concrete_Thickness" : float(self.Concrete_thickness_lineEdit.text()),
                "Current_Velocity" : float(self.Current_Velocity_lineEdit.text()),
                "Wave_Velocity" : float(self.Wave_velocity_lineEdit.text()),
                "Operational_temperature" :float(self.Operational_temparature_lineEdit.text()),
                "Installation_temperature" :float(self.Installation_temperature_lineEdit.text()),
                "Internal_pressure" : float(self.Installation_temperature_lineEdit.text()),
                "Yield_Strength" : yield_strength,
                "Beta_Value" : beta,
                "Deflection_Factor" : deflection_factor,
                "Moment_Factor" : moment_factor,
                "Test_Case" : test_case,
                "Content_Type" : self.Content_Type_case_Combobox.currentText() if self.Content_Type_case_Combobox.isEnabled() else None,
                "Content_Density" : content_density,
                "Deflection_Criteria" : self.deflection_criteria
            }
            print("Frontend data collected: ", frontendData)
            
            self.result = freeSpan_Analysis_calculation(frontendData)
            self.displayFreespanResults(self.result)

            self.ShowMore_pushButton.setDisabled(False)
            

        except Exception as e:
            print("Error in inputData function: ", e)
            self.Result_textEdit.setText("Error occurred while processing input data. " + str(e))
            QtWidgets.QMessageBox.critical(None, "Error", "Please fill all fields & try again ❌")

    # --------------------------button connected------------------------------------

    

        

    def displayFreespanResults(self, result):
        self.Result_textEdit.clear()
        

        try:

            self.L_by_D_check.setText("L/D Check")

            print(result)
            print("LD_Check =", result.get("LD_Check"))

            status = result["LD_Check"]
            color = "green" if status == "PASS" else "red"
            self.L_by_D_check.setText(f"L/D ratio:  {status}")

            self.L_by_D_check.setStyleSheet(f"""
            color: white;
            background-color: {color};
            padding: 3px;
            border-radius: 6px;
            font-weight: bold;
        """)

        
            if status == "FAIL":
                self.Result_textEdit.setText(result.get("message", "L/D ratio not acceptable as L/D < 140. No further calculations done"))
                return

            if "error" in result:
                self.Result_textEdit.setText(result["error"])
            else:
                now = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

                 # HEADER
                self.Result_textEdit.append("========== FREE SPAN ANALYSIS ==========\n")
                self.Result_textEdit.append(f"Result Updated: {now}")
                self.Result_textEdit.append("Version: 0.0.1\n")

                # GEOMETRY
                self.Result_textEdit.append("----- PIPE GEOMETRY -----")
                self.Result_textEdit.append(f"Steel Area                          : {result['Steel_Area']:.3f}")
                self.Result_textEdit.append(f"Outer Dia (Coated)                  : {result['Outer_Diameter_after_Coating']:.3f}")
                self.Result_textEdit.append(f"Outer Dia (Concrete)                : {result['Outer_Diameter_after_Concrete']:.3f}")
                self.Result_textEdit.append(f"Total Outer Diameter                : {result['Outer_Diameter_including_coating_concrete']:.3f}\n")

                # MASS & FORCES
                self.Result_textEdit.append("----- MASS & FORCES -----")
                self.Result_textEdit.append(f"Submerged Mass                      : {result['Submerged_Mass']:.3f}")
                self.Result_textEdit.append(f"Submerged Weight                    : {result['Submerged_Weight']:.3f}")
                self.Result_textEdit.append(f"Buoyancy                            : {result['Buoyancy']:.3f}")
                self.Result_textEdit.append(f"Total Mass                          : {result['Total']:.3f}\n")

                # STRUCTURAL
                self.Result_textEdit.append("----- STRUCTURAL RESPONSE -----")
                self.Result_textEdit.append(f"Bending Stiffness (I)               : {result['Bending_Stiffness']:.3f}")
                self.Result_textEdit.append(f"Flexural Rigidity (EI)              : {result['Bending_Stiffness_EI']:.3f}")
                self.Result_textEdit.append(f"Deflection Value                    : {result['Deflection_value']:.3f}")
                self.Result_textEdit.append(f"Deflection Status                   : {result['Deflection_status']}")
                self.Result_textEdit.append(f"Stress Rho                          : {result['stress_rho']:.3f}")
                self.Result_textEdit.append(f"BendingStress Status                : {result['BendingStress_status']}")
                self.Result_textEdit.append(f"Bending Moment                      : {result['Bending_Stress_Moment']:.3f}\n")

                # FLOW
                self.Result_textEdit.append("----- HYDRODYNAMICS -----")
                self.Result_textEdit.append(f"Flow Regime                         : {result['alpha']:.3f}")
                self.Result_textEdit.append(f"Flow Regime Status                  : {result['Flow_Regime_status']}")
                self.Result_textEdit.append(f"Reduced Velocity                    : {result['Reduced_velocity']:.3f}")
                self.Result_textEdit.append(f"VIV_Status                          : {result['VIV_Status']}\n")

                # FATIGUE
                self.Result_textEdit.append("----- FATIGUE ANALYSIS -----")
                self.Result_textEdit.append(f"Fatigue Damage                      : {result['D_fat']:.3f}")
                self.Result_textEdit.append(f"SN Curve Life (N)                   : {result['SN_Curve_for_N']:.3e}")
                self.Result_textEdit.append(f"Number of Cycles                    : {result['Number_of_cycle_n']:.3e}")
                self.Result_textEdit.append(f"Fatigue Status                      : {result['Fatigue_status']}\n")

                # ULTIMATE
                self.Result_textEdit.append("----- ULTIMATE LIMIT STATE -----")
                self.Result_textEdit.append(f"Allowable Stress                    : {result['Allowable_Stress']:.3f}")
                self.Result_textEdit.append(f"Unity Check                         : {result['Unity_check']:.3f}")
                self.Result_textEdit.append(f"ULS Status                          : {result['ULS_status']}\n")

                # FOOTER
                self.Result_textEdit.append("======================================")
                self.Result_textEdit.append("© 2026 ASHKAM Energy Pvt. Ltd.")


                self.plot_SN_curve(result)
                        
        except Exception as e:
            print("Error: IN DISPLAYING RESULTS => ", e)
            QtWidgets.QMessageBox.critical(None, "Error", "Error occurred while displaying results. Please try again. ❌")
            self.Result_textEdit.setText("Error occurred while displaying results. Please try again. ❌" + str(e))
            

    def reset_all(self, MainWindow):
        print("Started Resetting all inputs now.............WAIT!")
        try:

            # Reset all input fields
            self.Project_lineEdit.clear()
            self.Project_Code_lineEdit.clear()
            self.Span_Length_lineEdit.clear()
            self.Outer_diameter_lineEdit.clear()
            self.Coating_Dessity_lineEdit.clear()
            self.Wall_thickness_lineEdit.clear()
            self.Coating_thickness_lineEdit.clear()
            self.Wave_velocity_lineEdit.clear()
            self.Current_Velocity_lineEdit.clear()
            self.Concrete_thickness_lineEdit.clear()
            self.L_by_D_check.clear()
            # self.L_by_D_check.setStyleSheet()

            self.Operational_temparature_lineEdit.clear()
            self.Installation_temperature_lineEdit.clear()
            self.Internal_pressure_lineEdit.clear()

            self.Result_textEdit.clear()
            self.ShowMore_pushButton.setDisabled(True)

            # Reset ComboBoxes
            self.Pipeline_Grade_comboBox.setCurrentIndex(0)
            self.Boundary_condition_comboBox.setCurrentIndex(0)
            self.select_test_case_combobox.setCurrentIndex(0)
            self.Content_Type_case_Combobox.setCurrentIndex(0)
            self.Deflection_factor_Combobox.setCurrentIndex(0)
            self.Expansion_condition_Constant.setCurrentIndex(0)

           
            print("Resetting completed successfully!")
            QtWidgets.QMessageBox.information(None, "Reset Successful", "All inputs have been reset successfully ✅")
        except Exception as e:
            print(f"Error during reset: {e}")
            print("Resetting failed. Please try again.")
            QtWidgets.QMessageBox.critical(None, "Error", "The inputs could not be reset. Please try again after resolving the issue. ❌" + str(e))
    


    # Function for saving the inputs

    def save_As(self):
        try:

            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                None, "Save File", "", "JSON Files (*.json)"
            )
            if not file_path:
                return

            if save_inputs(self.input_fields, file_path):
                print("Saved successfully")
            else:
                print("Save failed")

        except Exception as e:
            print("error: IN SAVE AS =>",e)
            QtWidgets.QMessageBox.critical(None, "Error", "The file could not be saved. Please try again after resolving the issue. ❌" + str(e))



      # Function for opening the saved inputs

    def openFile(self):
        try:

            file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
                None, "Open File", "", "JSON Files (*.json)"
            )
            if not file_path:
                return

            if load_inputs_mapped(file_path, self.input_fields):
                print("Loaded successfully")
            else:
                print("Load failed")
        except Exception as e:
            print("error: IN OPEN FILE => ", e)
            QtWidgets.QMessageBox.critical(None, "Error", "The file could not be opened. Please try again after resolving the issue. ❌" + str(e))


    # function for genrated by & verified by input 
    def get_user_info(self):
        try :
            
            dialog = QtWidgets.QDialog()
            dialog.setWindowTitle("Enter Report Details")

            layout = QtWidgets.QFormLayout(dialog)

            generated_by_input = QtWidgets.QLineEdit()
            verified_by_input = QtWidgets.QLineEdit()

            layout.addRow("Generated By:", generated_by_input)
            layout.addRow("Verified By:", verified_by_input)

            buttons = QtWidgets.QDialogButtonBox(
                QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel
            )

            layout.addWidget(buttons)

            buttons.accepted.connect(dialog.accept)
            buttons.rejected.connect(dialog.reject)

            if dialog.exec_() == QtWidgets.QDialog.Accepted:
                return generated_by_input.text(), verified_by_input.text()
            else:
                return None, None
        except Exception as e:
            print("Error: IN GET USER INFO => ", e)
            QtWidgets.QMessageBox.critical(None, "Error", "Error occurred while fetching user information. Please try again. ❌")
            
            

    def generate_report(self):

        try:

            outputs = {}

            if hasattr(self, "result") and isinstance(self.result, dict):

                outputs = {
                    "L/D Check": self.result.get("LD_Check", ""),
                    "Steel Area ": f"{self.result.get("Steel_Area", "")} m²",
                    "Outer Diameter After Coating (kg/m)": f"{self.result.get("Outer_Diameter_after_Coating", "")} m",
                    "Outer Diameter After Concrete": f"{self.result.get("Outer_Diameter_after_Concrete", "")} m",
                    "Submerged Mass": f"{self.result.get("Submerged_Mass", "")} Kg/m",
                    "Submerged Weight": f"{self.result.get("Submerged_Weight", "")} N/m",
                    "Buoyancy": f"{self.result.get("Buoyancy", "")} ",
                    "Total Mass of the section of pipe occupied": f"{self.result.get("Total", "")} Kg/m",
                    "Bending Stiffness": f"{self.result.get("Bending_Stiffness", "")}" ,
                    "Flexural Rigidity": f"{self.result.get("Bending_Stiffness_EI", "")} N/m²",
                    "Deflection Value": f"{self.result.get("Deflection_value", "")} m",
                    "Deflection Status": f"{self.result.get("Deflection_status", "")}",
                    "Stress Rho": f"{self.result.get("stress_rho", "")} Mpa",
                    "Bending Stress Status": f"{self.result.get("BendingStress_status", "")}",
                    "Bending Moment": f"{self.result.get("Bending_Stress_Moment", "")} Nm",
                    "Flow Regime": f"{self.result.get("alpha", "")}",
                    "Flow Regime Status": f"{self.result.get("Flow_Regime_status", "")}",
                    "Reduced Velocity": f"{self.result.get("Reduced_velocity", "")}",
                    "VIV Status": f"{self.result.get("VIV_Status", "")}",
                    "Fatigue Damage": f"{self.result.get("D_fat", "")}",
                    "SN Curve Life": f"{self.result.get("SN_Curve_for_N", "")}",
                    "Number of Cycles": f"{self.result.get("Number_of_cycle_n", "")}",
                    "Fatigue Status": f"{self.result.get("Fatigue_status", "")}",
                    "Allowable Stress": f"{self.result.get("Allowable_Stress", "")}",
                    "Unity Check": f"{self.result.get("Unity_check", "")}",
                    "ULS Status": f"{self.result.get("ULS_status", "")}"

                }


            def extract(widget):
                if isinstance(widget, QtWidgets.QLineEdit):
                    return widget.text()
                elif isinstance(widget, QtWidgets.QComboBox):
                    return widget.currentText()
                elif isinstance(widget, QtWidgets.QLabel):
                    return widget.text()
                return ""

            generated_by, verified_by = self.get_user_info()

            if not generated_by:
                print("User cancelled")
                return
            

            moduleName = self.Module_Name
            # inputs = {key: extract(widget) for key, widget in self.input_fields.items()}
            # outputs = {key: extract(widget) for key, widget in self.output_fields.items()}

            # print(outputs)

            
            inputs = {
                "Project Name": extract(self.Project_lineEdit),
                "Document Number": extract(self.Project_Code_lineEdit),
                "Pipeline Grade": self.Pipeline_Grade_comboBox.currentText(),
                "Boundary Condition": self.Boundary_condition_comboBox.currentText(),
                "Span Length": f"{extract(self.Span_Length_lineEdit)} m",
                "Outer Diameter": f"{extract(self.Outer_diameter_lineEdit)} m",
                "Coating Density": f"{extract(self.Coating_Dessity_lineEdit)} kg/m³",
                "Wall Thickness": f"{extract(self.Wall_thickness_lineEdit)} m",
                "Coating Thickness": f"{extract(self.Coating_thickness_lineEdit)} m",
                "Concrete Thickness": f"{extract(self.Concrete_thickness_lineEdit)} m",
                "Current Velocity": f"{extract(self.Current_Velocity_lineEdit)} m/s",
                "Wave Velocity": f"{extract(self.Wave_velocity_lineEdit)} m/s",
                
                }
            

            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                None, "Save Report", "", "PDF Files (*.pdf)"
            )

            if not file_path:
                return

            success = generate_report(moduleName, inputs, outputs, file_path, generated_by, verified_by)

            if success:
                QtWidgets.QMessageBox.information(None, "Success", "PDF Report generated successfully ✅")
            else:
                QtWidgets.QMessageBox.critical(None, "Failed", "Report generation failed ❌")

        except Exception as e:
            print("Error: IN GENERATE REPORT => ", e)
            # QtWidgets.QMessageBox.critical(None, "Error", "Error generating report ❌")
            QtWidgets.QMessageBox.critical(None, "Error", "The Report could not be opened. Please try again after resolving the issue. ❌" + str(e))




    def open_documentation(self):
        print("Documentation functionality is initialized")
        print("Documentation functionality is not implemented yet.")
        """Displays application documentation."""
        print("Action: Documentation")
        try :
            print("Documentation functionality is working fine")
            screen = open_screen(DocumentationScreenFreeSpan)
            self.open_windows.append(screen)
        except Exception as e:
            print("Error: IN OPEN DOCUMENTATION => ", e)
            # QtWidgets.QMessageBox.critical(None, "Error", "Error opening Documentation window ❌")
            QtWidgets.QMessageBox.critical(None, "Error", "The documentation could not be opened. Please try again after resolving the issue. ❌" + str(e))



    def open_whats_new(self):
        print("What's New functionality is initialized")
        try :
            print("What's New functionality is working fine")
            screen = open_screen(WhatsNewScreenFreeSpan)
            self.open_windows.append(screen)    
        except Exception as e:
            print("Error: IN OPEN WHAT'S NEW => ", e)
            # QtWidgets.QMessageBox.critical(None, "Error", "Error opening What's New window ❌")
            QtWidgets.QMessageBox.critical(None, "Error", "The What's New window could not be opened. Please try again after resolving the issue. ❌" + str(e))


    def plot_SN_curve(self, result):

        try:
            sn_data = result.get("SN_curve", [])
            stress_range = result.get("Stress_Range", {})

            if not sn_data:
                return

            self.sn_canvas.ax.clear()

            stress = [point[0] for point in sn_data]
            cycles = [point[1] for point in sn_data]

            self.sn_canvas.ax.plot(stress, cycles, marker='o')

            # 🔥 KEY: Prevent stretching
            self.sn_canvas.ax.set_box_aspect(0.6)

            # Log scale
            self.sn_canvas.ax.set_yscale('log')

            # Controlled margins
            self.sn_canvas.ax.margins(x=0.05, y=0.1)

            # Limits
            self.sn_canvas.ax.set_xlim(min(stress)*0.9, max(stress)*1.1)
            self.sn_canvas.ax.set_ylim(min(cycles)*0.8, max(cycles)*1.2)

            self.sn_canvas.ax.set_xlabel("Stress Range (MPa)")
            self.sn_canvas.ax.set_ylabel("Number of Cycles (N)")
            self.sn_canvas.ax.set_title("S-N Curve")
            self.sn_canvas.ax.grid(True)

            # Operating point
            if stress_range:
                actual_stress = stress_range.get("Stress", None)
                if actual_stress:
                    sn_value = result.get("SN_Curve_for_N")
                    self.sn_canvas.ax.scatter(
                        actual_stress,
                        sn_value,
                        color='red',
                        label='Operating Point'
                    )
                    self.sn_canvas.ax.legend()

            self.sn_canvas.figure.tight_layout()
            self.sn_canvas.draw()

        except Exception as e:
            print("Graph Error: IN PLOT SN CURVE => ", e)
            QtWidgets.QMessageBox.critical(None, "Error", "The S-N curve could not be plotted. Please try again after resolving the issue. ❌" + str(e))


    def open_summary_result(self):
        try:

            print("Summary Result part is initialized")
            print("TYPE:", type(self.result))
            print("RESULT:", self.result)

            if not isinstance(self.result, dict):
                print("ERROR: Result is not dictionary")
                return



            print("Summary Result part is initialized")
            screen = open_screen(ResultSummary, self.result)
            self.open_windows.append(screen)

        except Exception as e:
            print("error: IN OPEN SUMMARY RESULT => ", e)
            QtWidgets.QMessageBox.critical(None, "Error", "The summary result could not be opened. Please try again after resolving the issue. ❌" + str(e))
    
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FreeSpan Analysis"))

        self.INPUT_DATA.setTitle(_translate("MainWindow", "INPUT DATA"))
        self.Pipe_geometry.setText(_translate("MainWindow", "Pipe Geometry"))
        self.Environment.setText(_translate("MainWindow", "Environment"))
        self.Wall_thickness_label.setText(_translate("MainWindow", "Wall Thickness (m)               "))
        self.Coating_thickness_label.setText(_translate("MainWindow", "Coating Thickness (m)         "))
        self.Concrete_thickness_label.setText(_translate("MainWindow", "Concrete Thickness (m)       "))
        self.Internal_pressure_label.setText(_translate("MainWindow", "Internal Pressure (Pa)         "))
        self.Current_Velocity_label.setText(_translate("MainWindow", "Current Velocity (m/s)"))
        self.Wave_velocity_label.setText(_translate("MainWindow", "Wave Velocity (m/s)   "))
        self.Span_Length_label.setText(_translate("MainWindow", "Assumed span length L ( m)"))
        self.Outer_Diameter_label.setText(_translate("MainWindow", "Outer Diameter (m)             "))
        self.Expansion_condition_Constant.setCurrentText(_translate("MainWindow", "Select Expansion Condition Constant"))
        self.Expansion_condition_Constant.setItemText(0, _translate("MainWindow", "Select Expansion Condition Constant"))
        self.Expansion_condition_Constant.setItemText(1, _translate("MainWindow", "0"))
        self.Expansion_condition_Constant.setItemText(2, _translate("MainWindow", "0.3 - 0.8"))
        self.Expansion_condition_Constant.setItemText(3, _translate("MainWindow", "1"))
        self.Material_Property.setText(_translate("MainWindow", "Material Property"))
        self.Boundary_condition_comboBox.setCurrentText(_translate("MainWindow", "Select Boundary Condition"))
        self.Boundary_condition_comboBox.setItemText(0, _translate("MainWindow", "Select Boundary Condition"))
        self.Boundary_condition_comboBox.setItemText(1, _translate("MainWindow", "fixed-fixed"))
        self.Boundary_condition_comboBox.setItemText(2, _translate("MainWindow", "pinned-pinned"))
        self.Boundary_condition_comboBox.setItemText(3, _translate("MainWindow", "fixed-pinned"))
        # self.L_by_D_check.setText(_translate("MainWindow", "L/ D Ratio"))
        self.Pipeline_Grade_comboBox.setCurrentText(_translate("MainWindow", "Select Pipeline Grade"))
        self.Pipeline_Grade_comboBox.setItemText(0, _translate("MainWindow", "Select Pipeline Grade"))
        self.Pipeline_Grade_comboBox.setItemText(1, _translate("MainWindow", "A25"))
        self.Pipeline_Grade_comboBox.setItemText(2, _translate("MainWindow", "B"))
        self.Pipeline_Grade_comboBox.setItemText(3, _translate("MainWindow", "X42"))
        self.Pipeline_Grade_comboBox.setItemText(4, _translate("MainWindow", "X46"))
        self.Pipeline_Grade_comboBox.setItemText(5, _translate("MainWindow", "X52"))
        self.Pipeline_Grade_comboBox.setItemText(6, _translate("MainWindow", "X56"))
        self.Pipeline_Grade_comboBox.setItemText(7, _translate("MainWindow", "X60"))
        self.Pipeline_Grade_comboBox.setItemText(8, _translate("MainWindow", "X65"))
        self.Pipeline_Grade_comboBox.setItemText(9, _translate("MainWindow", "X70"))
        self.Pipeline_Grade_comboBox.setItemText(10, _translate("MainWindow", "X80"))
        self.Material_Property_2.setText(_translate("MainWindow", "L/ D ratio is always less than 140 "))
        self.Operational_temperature_label.setText(_translate("MainWindow", "Operational Temperature (° c)"))
        self.Installation_temperature_label.setText(_translate("MainWindow", "Installation Temperature (° c) "))
        self.Coating_density_label.setText(_translate("MainWindow", "Coating Density (kg/m3)"))
        self.select_test_case_combobox.setCurrentText(_translate("MainWindow", "Select Test Case"))
        self.select_test_case_combobox.setItemText(0, _translate("MainWindow", "Select Test Case"))
        self.select_test_case_combobox.setItemText(1, _translate("MainWindow", "Installation"))
        self.select_test_case_combobox.setItemText(2, _translate("MainWindow", "Hydrotest"))
        self.select_test_case_combobox.setItemText(3, _translate("MainWindow", "Operational"))
        self.Run_pushButton.setText(_translate("MainWindow", "RUN"))
        self.Content_Type_case_Combobox.setCurrentText(_translate("MainWindow", "Select Content Type"))
        self.Content_Type_case_Combobox.setItemText(0, _translate("MainWindow", "Select Content Type"))
        self.Content_Type_case_Combobox.setItemText(1, _translate("MainWindow", "Light Crude"))
        self.Content_Type_case_Combobox.setItemText(2, _translate("MainWindow", "Medium Crude"))
        self.Content_Type_case_Combobox.setItemText(3, _translate("MainWindow", "Heavy Crude"))
        self.Content_Type_case_Combobox.setItemText(4, _translate("MainWindow", "Condensate"))
        self.Content_Type_case_Combobox.setItemText(5, _translate("MainWindow", "Gas"))
        self.Deflection_factor_Combobox.setCurrentText(_translate("MainWindow", "Select Deflection factor"))
        self.Deflection_factor_Combobox.setItemText(0, _translate("MainWindow", "Select Deflection factor"))
        self.Deflection_factor_Combobox.setItemText(1, _translate("MainWindow", "Very Flexible"))
        self.Deflection_factor_Combobox.setItemText(2, _translate("MainWindow", "Moderate"))
        self.Deflection_factor_Combobox.setItemText(3, _translate("MainWindow", "Typical"))
        self.Deflection_factor_Combobox.setItemText(4, _translate("MainWindow", "Strict"))
        self.Deflection_factor_Combobox.setItemText(5, _translate("MainWindow", "Precision Structures"))

        self.Project_label.setText(_translate("MainWindow", "Project Name:"))
        self.Project_code_label.setText(_translate("MainWindow", "Document No. :"))
        self.RESULT_label.setText(_translate("MainWindow", "Result"))
        self.ShowMore_pushButton.setText(_translate("MainWindow", "Summary"))
        self.INPUT_DATA.setTitle(_translate("MainWindow", "INPUT DATA"))
        self.Span_Length_label.setText(_translate("MainWindow", "Assumed span length L ( m)"))
        self.Outer_Diameter_label.setText(_translate("MainWindow", "Outer Diameter (m)             "))
        self.L_by_D_check.setText(_translate("MainWindow", "L/ D Ratio"))
        self.Material_Property_2.setText(_translate("MainWindow", "L/ D ratio is always less than 140 "))
        self.Material_Property.setText(_translate("MainWindow", "Material Property"))
        self.Coating_density_label.setText(_translate("MainWindow", "Coating Density (kg/m3)"))
        self.Pipe_geometry.setText(_translate("MainWindow", "Pipe Geometry"))
        self.Wall_thickness_label.setText(_translate("MainWindow", "Wall Thickness (m)        "))
        self.Coating_thickness_label.setText(_translate("MainWindow", "Coating Thickness (m)  "))
        self.Concrete_thickness_label.setText(_translate("MainWindow", "Concrete Thickness (m)"))
        self.Environment.setText(_translate("MainWindow", "Environment"))
        self.Current_Velocity_label.setText(_translate("MainWindow", "Current Velocity (m/s)"))
        self.Wave_velocity_label.setText(_translate("MainWindow", "Wave Velocity (m/s)   "))
        self.Run_pushButton.setText(_translate("MainWindow", "RUN"))
        self.copyright_label.setText(_translate("MainWindow", "@2026  ASHKAM Energy Pvt. Ltd.  All rights reserved"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        # self.actionSave.setText(_translate("MainWindow", "Save As"))
        # self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Shift+R"))
        self.actionWhat_s_New.setText(_translate("MainWindow", "What\'s New"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionGenerate_Report.setText(_translate("MainWindow", "Generate Report"))




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

class FreeSpanAnalysis(QMainWindow):

    def __init__(self):
        super().__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)