# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FreeSpan_update1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from datetime import datetime
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import math

from calculations import freeSpan_Analysis_calculation

# from utils import save_inputs, load_inputs_mapped, generate_report, open_screen
# from utils import caseOption, get_all_inputs, get_required_inputs, DocumentationScreen, WhatsNewScreen, open_screen
# from utils import generate_report
# from utils import save_inputs, load_inputs_mapped, generate_report, open_screen
from utils import caseOption, get_all_inputs, get_required_inputs, DocumentationScreen, WhatsNewScreen, save_inputs, load_inputs_mapped, generate_report, ResultSummary, open_screen


__version__ = "0.0.1"
print(f"Loading On Free Span Analysis module version {__version__}...")


class SNGraphCanvas(FigureCanvas):
    def __init__(self, parent=None):
        self.figure = Figure(figsize=(5, 3))  # 👈 controls proportion
        self.ax = self.figure.add_subplot(111)
        super().__init__(self.figure)

        # Allow resizing
        self.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Expanding
        )



class Ui_MainWindow(object):

    # ----module name for report generation------

    Module_Name = "Free Span Analysis"

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 716)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../DPR-Pashupatinath/images/18.03.2026/Freespan.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.028, y1:0.0455909, x2:0.841, y2:0.966364, stop:0 rgba(169, 237, 255, 107), stop:0.994318 rgba(253, 255, 218, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.Project_label = QtWidgets.QLabel(self.groupBox_2)
        self.Project_label.setObjectName("Project_label")
        self.horizontalLayout_38.addWidget(self.Project_label)
        self.Project_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.Project_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Project_lineEdit.setObjectName("Project_lineEdit")
        self.horizontalLayout_38.addWidget(self.Project_lineEdit)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.Project_code_label = QtWidgets.QLabel(self.groupBox_2)
        self.Project_code_label.setObjectName("Project_code_label")
        self.horizontalLayout_37.addWidget(self.Project_code_label)
        self.Project_Code_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.Project_Code_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Project_Code_lineEdit.setObjectName("Project_Code_lineEdit")
        self.horizontalLayout_37.addWidget(self.Project_Code_lineEdit)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_37)
        self.gridLayout_5.addLayout(self.horizontalLayout_39, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 932, 231))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_SteelArea = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_SteelArea.setGeometry(10, 10, 300, 30)  # adjust as needed
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RESULT_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RESULT_label.setFont(font)
        self.RESULT_label.setObjectName("RESULT_label")
        self.gridLayout_2.addWidget(self.RESULT_label, 0, 0, 1, 1)
        self.Result_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Result_textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Result_textEdit.setObjectName("Result_textEdit")
        self.Result_textEdit.setReadOnly(True)  # Make it read-only
        self.gridLayout_2.addWidget(self.Result_textEdit, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(829, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 3, 0, 1, 2)

        self.sn_canvas = SNGraphCanvas(self.groupBox_2)
        self.sn_canvas.setStyleSheet("background-color: white;")
        self.gridLayout_5.addWidget(self.sn_canvas, 2, 1, 1, 1, QtCore.Qt.AlignTop)
        # Balance layout properly
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)

        self.gridLayout_5.setRowStretch(0, 0)
        self.gridLayout_5.setRowStretch(1, 0)
        self.gridLayout_5.setRowStretch(2, 1)  # 👈 graph row
        self.gridLayout_5.setRowStretch(3, 1)


        # self.graphicsView.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.graphicsView.setObjectName("graphicsView")
        # self.gridLayout_5.addWidget(self.graphicsView, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(336, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(451, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 1, 1, 1)
        self.ShowMore_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.ShowMore_pushButton.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.ShowMore_pushButton.setObjectName("ShowMore_pushButton")
        self.gridLayout_3.addWidget(self.ShowMore_pushButton, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.INPUT_DATA = QtWidgets.QGroupBox(self.groupBox_2)
        self.INPUT_DATA.setObjectName("INPUT_DATA")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.INPUT_DATA)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(115, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Span_Length_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Span_Length_label.setObjectName("Span_Length_label")
        self.horizontalLayout_17.addWidget(self.Span_Length_label)
        self.Span_Length_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Span_Length_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Span_Length_lineEdit.setObjectName("Span_Length_lineEdit")
        self.horizontalLayout_17.addWidget(self.Span_Length_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Outer_Diameter_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Outer_Diameter_label.setObjectName("Outer_Diameter_label")
        self.horizontalLayout_5.addWidget(self.Outer_Diameter_label)
        self.Outer_diameter_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Outer_diameter_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Outer_diameter_lineEdit.setObjectName("Outer_diameter_lineEdit")
        self.horizontalLayout_5.addWidget(self.Outer_diameter_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.L_by_D_check = QtWidgets.QLabel(self.INPUT_DATA)
        self.L_by_D_check.setObjectName("L_by_D_check")
        self.gridLayout_4.addWidget(self.L_by_D_check, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(69, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 1, 5, 1, 1)
        self.Material_Property_2 = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.Material_Property_2.setFont(font)
        self.Material_Property_2.setObjectName("Material_Property_2")
        self.gridLayout_4.addWidget(self.Material_Property_2, 2, 0, 1, 1)
        self.Material_Property = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Material_Property.setFont(font)
        self.Material_Property.setObjectName("Material_Property")
        self.gridLayout_4.addWidget(self.Material_Property, 2, 3, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Coating_density_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Coating_density_label.setObjectName("Coating_density_label")
        self.horizontalLayout.addWidget(self.Coating_density_label)
        self.Coating_Dessity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Coating_Dessity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Coating_Dessity_lineEdit.setObjectName("Coating_Dessity_lineEdit")
        self.horizontalLayout.addWidget(self.Coating_Dessity_lineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 3, 1, 3)
        self.Pipe_geometry = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pipe_geometry.setFont(font)
        self.Pipe_geometry.setObjectName("Pipe_geometry")
        self.gridLayout_4.addWidget(self.Pipe_geometry, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 4, 3, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Wall_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Wall_thickness_label.setObjectName("Wall_thickness_label")
        self.horizontalLayout_4.addWidget(self.Wall_thickness_label)
        self.Wall_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Wall_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Wall_thickness_lineEdit.setObjectName("Wall_thickness_lineEdit")
        self.horizontalLayout_4.addWidget(self.Wall_thickness_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Coating_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Coating_thickness_label.setObjectName("Coating_thickness_label")
        self.horizontalLayout_3.addWidget(self.Coating_thickness_label)
        self.Coating_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Coating_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Coating_thickness_lineEdit.setObjectName("Coating_thickness_lineEdit")
        self.horizontalLayout_3.addWidget(self.Coating_thickness_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Concrete_thickness_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Concrete_thickness_label.setObjectName("Concrete_thickness_label")
        self.horizontalLayout_2.addWidget(self.Concrete_thickness_label)
        self.Concrete_thickness_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Concrete_thickness_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Concrete_thickness_lineEdit.setObjectName("Concrete_thickness_lineEdit")
        self.horizontalLayout_2.addWidget(self.Concrete_thickness_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 5, 0, 3, 2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 6, 2, 1, 1)
        self.Environment = QtWidgets.QLabel(self.INPUT_DATA)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Environment.setFont(font)
        self.Environment.setObjectName("Environment")
        self.gridLayout_4.addWidget(self.Environment, 6, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Current_Velocity_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Current_Velocity_label.setObjectName("Current_Velocity_label")
        self.horizontalLayout_6.addWidget(self.Current_Velocity_label)
        self.Current_Velocity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Current_Velocity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Current_Velocity_lineEdit.setObjectName("Current_Velocity_lineEdit")
        self.horizontalLayout_6.addWidget(self.Current_Velocity_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Wave_velocity_label = QtWidgets.QLabel(self.INPUT_DATA)
        self.Wave_velocity_label.setObjectName("Wave_velocity_label")
        self.horizontalLayout_7.addWidget(self.Wave_velocity_label)
        self.Wave_velocity_lineEdit = QtWidgets.QLineEdit(self.INPUT_DATA)
        self.Wave_velocity_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Wave_velocity_lineEdit.setObjectName("Wave_velocity_lineEdit")
        self.horizontalLayout_7.addWidget(self.Wave_velocity_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 7, 3, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 7, 6, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(139, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 8, 4, 1, 2)
        self.Run_pushButton = QtWidgets.QPushButton(self.INPUT_DATA)
        self.Run_pushButton.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.Run_pushButton.setObjectName("Run_pushButton")
        self.gridLayout_4.addWidget(self.Run_pushButton, 8, 6, 1, 1)
        self.Pipeline_Grade_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        self.Pipeline_Grade_comboBox.setStyleSheet("")
        self.Pipeline_Grade_comboBox.setObjectName("Pipeline_Grade_comboBox")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.Pipeline_Grade_comboBox.addItem("")
        self.gridLayout_4.addWidget(self.Pipeline_Grade_comboBox, 0, 3, 1, 2)
        self.Boundary_condition_comboBox = QtWidgets.QComboBox(self.INPUT_DATA)
        self.Boundary_condition_comboBox.setStyleSheet("")
        self.Boundary_condition_comboBox.setObjectName("Boundary_condition_comboBox")
        self.Boundary_condition_comboBox.addItem("")
        self.Boundary_condition_comboBox.addItem("")
        self.Boundary_condition_comboBox.addItem("")
        self.Boundary_condition_comboBox.addItem("")
        self.gridLayout_4.addWidget(self.Boundary_condition_comboBox, 0, 5, 1, 2)
        self.gridLayout_5.addWidget(self.INPUT_DATA, 0, 0, 3, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 626, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 0, 2, 1, 1)
        self.copyright_label = QtWidgets.QLabel(self.centralwidget)
        self.copyright_label.setObjectName("copyright_label")
        self.gridLayout.addWidget(self.copyright_label, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(950, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/new.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:/SPIS/assets/open.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        # self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:/SPIS/assets/save_as.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName("actionSave_As")
        # self.actionSave_As = QtWidgets.QAction(MainWindow)
        # self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("E:/SPIS/assets/close.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("E:/SPIS/assets/reset.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset.setIcon(icon5)
        self.actionReset.setObjectName("actionReset")
        self.actionWhat_s_New = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("E:/SPIS/assets/What\'s new.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWhat_s_New.setIcon(icon6)
        self.actionWhat_s_New.setObjectName("actionWhat_s_New")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("E:/SPIS/assets/report.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentation.setIcon(icon7)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionGenerate_Report = QtWidgets.QAction(MainWindow)
        self.actionGenerate_Report.setIcon(icon7)
        self.actionGenerate_Report.setObjectName("actionGenerate_Report")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionReset)
        self.menuReport.addAction(self.actionGenerate_Report)
        self.menuHelp.addAction(self.actionWhat_s_New)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())


        self.input_fields = {
           "Project_Name" : self.Project_lineEdit,
           "Project Code ": self.Project_Code_lineEdit,
           "Span Length" : self.Span_Length_lineEdit,
           "Outer Diameter" : self.Outer_diameter_lineEdit,
           "Coating Density" : self.Coating_Dessity_lineEdit,
           "Wall Thickness" : self.Wall_thickness_lineEdit,
           "Coating Thickness" : self.Coating_thickness_lineEdit,
           "Concrete Thickness" : self.Concrete_thickness_lineEdit,
           "Current Velocity" : self.Current_Velocity_lineEdit,
           "Wave Velocity" : self.Wave_velocity_lineEdit,
        }

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Run_pushButton.clicked.connect(self.inputData)
        self.ShowMore_pushButton.clicked.connect(self.open_summary_result)



#--------------------------------------------------Functions are from here--------------------------------------------------------------

         # Menu bar functions
        self.actionReset.triggered.connect(self.reset_all)
        self.actionSave_As.triggered.connect(self.save_As)
        self.actionOpen.triggered.connect(self.openFile)
        self.actionGenerate_Report.triggered.connect(self.generate_report)
        self.actionDocumentation.triggered.connect(self.open_documentation)
        self.actionWhat_s_New.triggered.connect(self.open_whats_new)
        
        self.open_windows = []




    def inputData(self):
        print("This function is working")

        frontendData = {
            "Assumed_Span_Length" : float(self.Span_Length_lineEdit.text()),
            "Outer_Diameter" : float(self.Outer_diameter_lineEdit.text()),
            "Coating_Density" : float(self.Coating_Dessity_lineEdit.text()),
            "Wall_Thickness" : float(self.Wall_thickness_lineEdit.text()),
            "Coating_Thickness" : float(self.Coating_thickness_lineEdit.text()),
            "Concrete_Thickness" : float(self.Concrete_thickness_lineEdit.text()),
            "Current_Velocity" : float(self.Current_Velocity_lineEdit.text()),
            "Wave_Velocity" : float(self.Wave_velocity_lineEdit.text())


        }

        # print(frontendData)
        self.result = freeSpan_Analysis_calculation(frontendData)
        self.displayFreespanResults(self.result)

    # --------------------------button connected------------------------------------

    

        

    def displayFreespanResults(self, result):
        self.Result_textEdit.clear()
        

        try:

            self.L_by_D_check.setText("L/D Check")

            status = result["LD_Check"]
            color = "green" if status == "PASS" else "red"
            self.L_by_D_check.setText(f"L/D ratio:  {status}")

            self.L_by_D_check.setStyleSheet(f"""
            color: white;
            background-color: {color};
            padding: 3px;
            border-radius: 6px;
            font-weight: bold;
        """)

        
            if status == "FAIL":
                self.Result_textEdit.setText(result.get("message", "L/D ratio not acceptable as L/D < 140. No further calculations done"))
                return

            if "error" in result:
                self.Result_textEdit.setText(result["error"])
            else:
                now = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

                 # HEADER
                self.Result_textEdit.append("========== FREE SPAN ANALYSIS ==========\n")
                self.Result_textEdit.append(f"Result Updated: {now}")
                self.Result_textEdit.append("Version: 0.0.1\n")

                # GEOMETRY
                self.Result_textEdit.append("----- PIPE GEOMETRY -----")
                self.Result_textEdit.append(f"Steel Area                          : {result['Steel_Area']:.3f}")
                self.Result_textEdit.append(f"Outer Dia (Coated)                  : {result['Outer_Diameter_after_Coating']:.3f}")
                self.Result_textEdit.append(f"Outer Dia (Concrete)                : {result['Outer_Diameter_after_Concrete']:.3f}")
                self.Result_textEdit.append(f"Total Outer Diameter                : {result['Outer_Diameter_including_coating_concrete']:.3f}\n")

                # MASS & FORCES
                self.Result_textEdit.append("----- MASS & FORCES -----")
                self.Result_textEdit.append(f"Submerged Mass                      : {result['Submerged_Mass']:.3f}")
                self.Result_textEdit.append(f"Submerged Weight                    : {result['Submerged_Weight']:.3f}")
                self.Result_textEdit.append(f"Buoyancy                            : {result['Buoyancy']:.3f}")
                self.Result_textEdit.append(f"Total Mass                          : {result['Total']:.3f}\n")

                # STRUCTURAL
                self.Result_textEdit.append("----- STRUCTURAL RESPONSE -----")
                self.Result_textEdit.append(f"Bending Stiffness (I)               : {result['Bending_Stiffness']:.3f}")
                self.Result_textEdit.append(f"Flexural Rigidity (EI)              : {result['Bending_Stiffness_EI']:.3f}")
                self.Result_textEdit.append(f"Deflection Value                    : {result['Deflection_value']:.3f}")
                self.Result_textEdit.append(f"Deflection Status                   : {result['Deflection_status']}")
                self.Result_textEdit.append(f"Stress Rho                          : {result['stress_rho']:.3f}")
                self.Result_textEdit.append(f"BendingStress Status                : {result['BendingStress_status']}")
                self.Result_textEdit.append(f"Bending Moment                      : {result['Bending_Stress_Moment']:.3f}\n")

                # FLOW
                self.Result_textEdit.append("----- HYDRODYNAMICS -----")
                self.Result_textEdit.append(f"Flow Regime                         : {result['alpha']:.3f}")
                self.Result_textEdit.append(f"Flow Regime Status                  : {result['Flow_Regime_status']}")
                self.Result_textEdit.append(f"Reduced Velocity                    : {result['Reduced_velocity']:.3f}")
                self.Result_textEdit.append(f"VIV_Status                          : {result['VIV_Status']}")

                # FATIGUE
                self.Result_textEdit.append("----- FATIGUE ANALYSIS -----")
                self.Result_textEdit.append(f"Fatigue Damage                      : {result['D_fat']:.3f}")
                self.Result_textEdit.append(f"SN Curve Life (N)                   : {result['SN_Curve_for_N']:.3e}")
                self.Result_textEdit.append(f"Number of Cycles                    : {result['Number_of_cycle_n']:.3e}")
                self.Result_textEdit.append(f"Fatigue Status                      : {result['Fatigue_status']}\n")

                # ULTIMATE
                self.Result_textEdit.append("----- ULTIMATE LIMIT STATE -----")
                self.Result_textEdit.append(f"Allowable Stress                    : {result['Allowable_Stress']:.3f}")
                self.Result_textEdit.append(f"Unity Check                         : {result['Unity_check']:.3f}")
                self.Result_textEdit.append(f"ULS Status                          : {result['ULS_status']}\n")

                # FOOTER
                self.Result_textEdit.append("======================================")
                self.Result_textEdit.append("© 2026 ASHKAM Energy Pvt. Ltd.")


                self.plot_SN_curve(result)
                print("SN DATA:", result.get("SN_curve"))
                        
        except Exception as e:

            print("Error", e)


    def reset_all(self, MainWindow):
        print("Started Resetting all inputs now.............WAIT!")
        try:

            # Reset all input fields
            self.Project_lineEdit.clear()
            self.Project_Code_lineEdit.clear()
            self.Span_Length_lineEdit.clear()
            self.Outer_diameter_lineEdit.clear()
            self.Coating_Dessity_lineEdit.clear()
            self.Wall_thickness_lineEdit.clear()
            self.Coating_thickness_lineEdit.clear()
            self.Wave_velocity_lineEdit.clear()
            self.Current_Velocity_lineEdit.clear()
            self.Concrete_thickness_lineEdit.clear()
            self.Pipeline_Grade_comboBox.clear()
            self.Boundary_condition_comboBox.clear()
            self.L_by_D_check.clear()
            # self.L_by_D_check.setStyleSheet()

            self.Result_textEdit.clear()

           
            print("Resetting completed successfully!")
        except Exception as e:
            print(f"Error during reset: {e}")
            print("Resetting failed. Please try again.")
    


    # Function for saving the inputs

    def save_As(self):
        try:

            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                None, "Save File", "", "JSON Files (*.json)"
            )
            if not file_path:
                return

            if save_inputs(self.input_fields, file_path):
                print("Saved successfully")
            else:
                print("Save failed")

        except Exception as e:
            print("error",e)



      # Function for opening the saved inputs

    def openFile(self):
        try:

            file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
                None, "Open File", "", "JSON Files (*.json)"
            )
            if not file_path:
                return

            if load_inputs_mapped(file_path, self.input_fields):
                print("Loaded successfully")
            else:
                print("Load failed")
        except Exception as e:
            print("error", e)


    # function for genrated by & verified by input 
    def get_user_info(self):
        dialog = QtWidgets.QDialog()
        dialog.setWindowTitle("Enter Report Details")

        layout = QtWidgets.QFormLayout(dialog)

        generated_by_input = QtWidgets.QLineEdit()
        verified_by_input = QtWidgets.QLineEdit()

        layout.addRow("Generated By:", generated_by_input)
        layout.addRow("Verified By:", verified_by_input)

        buttons = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel
        )

        layout.addWidget(buttons)

        buttons.accepted.connect(dialog.accept)
        buttons.rejected.connect(dialog.reject)

        if dialog.exec_() == QtWidgets.QDialog.Accepted:
            return generated_by_input.text(), verified_by_input.text()
        else:
            return None, None



    def generate_report(self):

        try:
            def extract(widget):
                if isinstance(widget, QtWidgets.QLineEdit):
                    return widget.text()
                elif isinstance(widget, QtWidgets.QComboBox):
                    return widget.currentText()
                elif isinstance(widget, QtWidgets.QLabel):
                    return widget.text()
                return ""

            generated_by, verified_by = self.get_user_info()

            if not generated_by:
                print("User cancelled")
                return
            

            moduleName = self.Module_Name
            inputs = {key: extract(widget) for key, widget in self.input_fields.items()}
            # outputs = {key: extract(widget) for key, widget in self.output_fields.items()}

            # print(outputs)

            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                None, "Save Report", "", "PDF Files (*.pdf)"
            )

            if not file_path:
                return

            success = generate_report(moduleName, inputs, self.result, file_path, generated_by, verified_by)

            if success:
                QtWidgets.QMessageBox.information(None, "Success", "PDF Report generated successfully ✅")
            else:
                QtWidgets.QMessageBox.critical(None, "Failed", "Report generation failed ❌")

        except Exception as e:
            print("Error:", e)
            QtWidgets.QMessageBox.critical(None, "Error", "Error generating report ❌")




    def open_documentation(self):
        print("Documentation functionality is initialized")
        self.Result_textEdit.setText("Documentation functionality is not implemented yet.")
        """Displays application documentation."""
        print("Action: Documentation")
        screen = open_screen(DocumentationScreen)
        self.open_windows.append(screen)



    def open_whats_new(self):
        print("What's New functionality is initialized")
        self.Result_textEdit.setText("What's New functionality is not implemented yet.")
        screen = open_screen(WhatsNewScreen)
        self.open_windows.append(screen)       


    def plot_SN_curve(self, result):

        try:
            sn_data = result.get("SN_curve", [])
            stress_range = result.get("Stress_Range", {})

            if not sn_data:
                return

            self.sn_canvas.ax.clear()

            stress = [point[0] for point in sn_data]
            cycles = [point[1] for point in sn_data]

            self.sn_canvas.ax.plot(stress, cycles, marker='o')

            # 🔥 KEY: Prevent stretching
            self.sn_canvas.ax.set_box_aspect(0.6)

            # Log scale
            self.sn_canvas.ax.set_yscale('log')

            # Controlled margins
            self.sn_canvas.ax.margins(x=0.05, y=0.1)

            # Limits
            self.sn_canvas.ax.set_xlim(min(stress)*0.9, max(stress)*1.1)
            self.sn_canvas.ax.set_ylim(min(cycles)*0.8, max(cycles)*1.2)

            self.sn_canvas.ax.set_xlabel("Stress Range (MPa)")
            self.sn_canvas.ax.set_ylabel("Number of Cycles (N)")
            self.sn_canvas.ax.set_title("S-N Curve")
            self.sn_canvas.ax.grid(True)

            # Operating point
            if stress_range:
                actual_stress = stress_range.get("Stress", None)
                if actual_stress:
                    sn_value = result["fatigue"][1]

                    self.sn_canvas.ax.scatter(
                        actual_stress,
                        sn_value,
                        color='red',
                        label='Operating Point'
                    )
                    self.sn_canvas.ax.legend()

            self.sn_canvas.figure.tight_layout()
            self.sn_canvas.draw()

        except Exception as e:
            print("Graph Error:", e)


    def open_summary_result(self):
        try:

            print("Summary Result part is initialized")
            print("TYPE:", type(self.result))
            print("RESULT:", self.result)

            if not isinstance(self.result, dict):
                print("ERROR: Result is not dictionary")
                return



            print("Summary Result part is initialized")
            screen = open_screen(ResultSummary, self.result)
            self.open_windows.append(screen)

        except Exception as e:
            print("error", e)
    
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FreeSpan Analysis"))
        self.Project_label.setText(_translate("MainWindow", "Project Name:"))
        self.Project_code_label.setText(_translate("MainWindow", "Document No. :"))
        self.RESULT_label.setText(_translate("MainWindow", "Result"))
        self.ShowMore_pushButton.setText(_translate("MainWindow", "Show more"))
        self.INPUT_DATA.setTitle(_translate("MainWindow", "INPUT DATA"))
        self.Span_Length_label.setText(_translate("MainWindow", "Assumed span length L ( m)"))
        self.Outer_Diameter_label.setText(_translate("MainWindow", "Outer Diameter (m)             "))
        self.L_by_D_check.setText(_translate("MainWindow", "L/ D Ratio"))
        self.Material_Property_2.setText(_translate("MainWindow", "L/ D ratio is always less than 140 "))
        self.Material_Property.setText(_translate("MainWindow", "Material Property"))
        self.Coating_density_label.setText(_translate("MainWindow", "Coating Density (kg/m3)"))
        self.Pipe_geometry.setText(_translate("MainWindow", "Pipe Geometry"))
        self.Wall_thickness_label.setText(_translate("MainWindow", "Wall Thickness (m)        "))
        self.Coating_thickness_label.setText(_translate("MainWindow", "Coating Thickness (m)  "))
        self.Concrete_thickness_label.setText(_translate("MainWindow", "Concrete Thickness (m)"))
        self.Environment.setText(_translate("MainWindow", "Environment"))
        self.Current_Velocity_label.setText(_translate("MainWindow", "Current Velocity (m/s)"))
        self.Wave_velocity_label.setText(_translate("MainWindow", "Wave Velocity (m/s)   "))
        self.Run_pushButton.setText(_translate("MainWindow", "RUN"))
        self.Pipeline_Grade_comboBox.setItemText(0, _translate("MainWindow", "Pipeline Grade"))
        self.Pipeline_Grade_comboBox.setItemText(1, _translate("MainWindow", "A25"))
        self.Pipeline_Grade_comboBox.setItemText(2, _translate("MainWindow", "B"))
        self.Pipeline_Grade_comboBox.setItemText(3, _translate("MainWindow", "X42"))
        self.Pipeline_Grade_comboBox.setItemText(4, _translate("MainWindow", "X46"))
        self.Pipeline_Grade_comboBox.setItemText(5, _translate("MainWindow", "X52"))
        self.Pipeline_Grade_comboBox.setItemText(6, _translate("MainWindow", "X56"))
        self.Pipeline_Grade_comboBox.setItemText(7, _translate("MainWindow", "X60"))
        self.Pipeline_Grade_comboBox.setItemText(8, _translate("MainWindow", "X65"))
        self.Pipeline_Grade_comboBox.setItemText(9, _translate("MainWindow", "X70"))
        self.Pipeline_Grade_comboBox.setItemText(10, _translate("MainWindow", "X80"))
        self.Boundary_condition_comboBox.setItemText(0, _translate("MainWindow", "Boundary Condition"))
        self.Boundary_condition_comboBox.setItemText(1, _translate("MainWindow", "fixed-fixed"))
        self.Boundary_condition_comboBox.setItemText(2, _translate("MainWindow", "pinned-pinned"))
        self.Boundary_condition_comboBox.setItemText(3, _translate("MainWindow", "fixed-pinned"))
        self.copyright_label.setText(_translate("MainWindow", "@2026  ASHKAM Energy Pvt. Ltd.  All rights reserved"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        # self.actionSave.setText(_translate("MainWindow", "Save As"))
        # self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Shift+R"))
        self.actionWhat_s_New.setText(_translate("MainWindow", "What\'s New"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionGenerate_Report.setText(_translate("MainWindow", "Generate Report"))




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

class FreeSpanAnalysis(QMainWindow):

    def __init__(self):
        super().__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

