import csv
from PyQt5 import QtWidgets
import pandas as pd
from tkinter import filedialog
import random
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtWidgets
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import PageBreak
import json


def get_field_value(field):
    """Extract value from QLineEdit / QComboBox safely"""
    try:
        return field.text()  # QLineEdit
    except:
        try:
            return field.currentText()  # QComboBox
        except:
            return str(field)



def generate_report(input_fields, output_fields, file_path, generated_by, verified_by):
    try:
        doc = SimpleDocTemplate(file_path, pagesize=A4)
        elements = []
        styles = getSampleStyleSheet()

        # -------- Wrap Style (IMPORTANT for text wrapping) --------
        wrap_style = ParagraphStyle(
            'wrap',
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            wordWrap='CJK'
        )

        # -------- Helper Function --------
        def get_field_value(widget):
            if hasattr(widget, "text"):
                return widget.text()
            elif hasattr(widget, "currentText"):
                return widget.currentText()
            return str(widget)

        # -------- Clean Inputs --------
        clean_inputs = {k: get_field_value(v) for k, v in input_fields.items()}

        # -------- Extract Project Info --------
        project_name = clean_inputs.get("Project Name", "")
        document_number = clean_inputs.get("Document Number", "")

        filtered_inputs = {
            k: v for k, v in clean_inputs.items()
            if k not in ["Project Name", "Document Number"]
        }

        # -------- Title --------
        elements.append(Paragraph("On Bottom Stability Analysis", styles['Title']))
        elements.append(Spacer(1, 20))

        # -------- Header Table --------
        header_data = [
            ["Report Date:", datetime.now().strftime("%B %d, %Y %H:%M:%S")],
            ["Project Name:", project_name],
            ["Document Number:", document_number],
            ["Generated By:", generated_by],
            ["Verified By:", verified_by]
        ]

        header_table = Table(header_data, colWidths=[200, 250])
        header_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))

        elements.append(header_table)
        elements.append(Spacer(1, 20))

        

        # -------- Inputs Table --------
        elements.append(Paragraph("Inputs", styles['Heading2']))
        elements.append(Spacer(1, 12))

        input_data = [["Parameter", "Value"]]

        for key, value in filtered_inputs.items():
            input_data.append([
                Paragraph(str(key), wrap_style),
                Paragraph(str(value), wrap_style)
            ])

        input_table = Table(input_data, colWidths=[220, 250])
        input_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))

        elements.append(input_table)
        elements.append(Spacer(1, 20))

        elements.append(PageBreak())

        # -------- Clean Outputs --------
        clean_outputs = {k: get_field_value(v) for k, v in output_fields.items()}

        # -------- Outputs Table --------
        elements.append(Paragraph("Results", styles['Heading2']))
        elements.append(Spacer(1, 12))

        output_data = [["Output", "Value"]]

        for key, value in clean_outputs.items():
            output_data.append([
                Paragraph(str(key), wrap_style),
                Paragraph(str(value), wrap_style)
            ])

        output_table = Table(output_data, colWidths=[220, 250])
        output_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))

        elements.append(output_table)

        # -------- Build PDF --------
        doc.build(elements)

        print(f"PDF saved at: {file_path}")
        return True

    except Exception as e:
        print("PDF Error:", e)
        return False


def show_whats_new(self):
    """Displays information about new features."""
    print("Action: What's New?")
    QtWidgets.QMessageBox.information(self, "What's New?",
                                    "Version 1.0.1\n\n"
                                    "- Implemented combobox selection logic.\n"
                                    "- Added action button functionality.\n"
                                    "- Console output for all inputs.\n"
                                    "- Corrected Barlow Stress calculation formula.")

def show_documentation(self):
    """Displays application documentation."""
    print("Action: Documentation")
    QtWidgets.QMessageBox.information(self, "Documentation",
                                    "Detailed documentation will be available here.\n"
                                    "For now, please refer to the input labels for guidance. (Placeholder)")
    # You could open a local PDF/HTML file or an online link here
    # Example: QtGui.QDesktopServices.openUrl(QtCore.QUrl("file:///path/to/your/documentation.pdf"))


