import csv
from PyQt5 import QtWidgets
import pandas as pd
from tkinter import filedialog
import random
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtWidgets
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import PageBreak



__version__ = "0.0.1"
print(f"Loading Tool Bar Controls for version {__version__}...")



# --- Action Button Handlers ---
def new_file(self):
    """Resets all inputs for a new simulation."""
    print("Action: New File")
    self.reset_all_inputs()
    QtWidgets.QMessageBox.information(self, "New File", "All inputs have been reset for a new simulation.")

def open_file(self):
    """Opens an existing simulation file."""
    print("Action: Open File")
    file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Open Simulation", "", "Simulation Files (*.sim);;All Files (*)")
    if file_path:
        print(f"Opening file: {file_path}")
        QtWidgets.QMessageBox.information(self, "Open File", f"Attempting to open: {file_path}\n(File loading logic not implemented yet)")
        # TODO: Implement actual file loading logic here.
        # You would read the content of the file (e.g., JSON or CSV)
        # and populate the UI fields accordingly.
    else:
        print("File open cancelled.")

def save_file_as(self):
    """Saves the current simulation data to a new file."""
    print("Action: Save File As")
    file_path, _ = QtWidgets.QFileDialog.getSaveFileName(self, "Save Simulation As", "", "Simulation Files (*.sim);;All Files (*)")
    if file_path:
        print(f"Saving file as: {file_path}")
        QtWidgets.QMessageBox.information(self, "Save File As", f"Attempting to save to: {file_path}\n(File saving logic not implemented yet)")
        # TODO: Implement actual file saving logic here.
        # You would gather all current input and output values from the UI
        # and write them to the specified file (e.g., in JSON format).
    else:
        print("File save cancelled.")


def get_field_value(field):
    """Extract value from QLineEdit / QComboBox safely"""
    try:
        return field.text()  # QLineEdit
    except:
        try:
            return field.currentText()  # QComboBox
        except:
            return str(field)



def generate_report(input_fields, output_fields, file_path, generated_by, verified_by):
    try:
        doc = SimpleDocTemplate(file_path, pagesize=A4)
        elements = []
        styles = getSampleStyleSheet()

        # -------- Wrap Style (IMPORTANT for text wrapping) --------
        wrap_style = ParagraphStyle(
            'wrap',
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            wordWrap='CJK'
        )

        # -------- Helper Function --------
        def get_field_value(widget):
            if hasattr(widget, "text"):
                return widget.text()
            elif hasattr(widget, "currentText"):
                return widget.currentText()
            return str(widget)

        # -------- Clean Inputs --------
        clean_inputs = {k: get_field_value(v) for k, v in input_fields.items()}

        # -------- Extract Project Info --------
        project_name = clean_inputs.get("Project Name", "")
        document_number = clean_inputs.get("Document Number", "")

        filtered_inputs = {
            k: v for k, v in clean_inputs.items()
            if k not in ["Project Name", "Document Number"]
        }

        # -------- Title --------
        elements.append(Paragraph("On Bottom Stability Analysis", styles['Title']))
        elements.append(Spacer(1, 20))

        # -------- Header Table --------
        header_data = [
            ["Report Date:", datetime.now().strftime("%B %d, %Y %H:%M:%S")],
            ["Project Name:", project_name],
            ["Document Number:", document_number],
            ["Generated By:", generated_by],
            ["Verified By:", verified_by]
        ]

        header_table = Table(header_data, colWidths=[200, 250])
        header_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))

        elements.append(header_table)
        elements.append(Spacer(1, 20))

        

        # -------- Inputs Table --------
        elements.append(Paragraph("Inputs", styles['Heading2']))
        elements.append(Spacer(1, 12))

        input_data = [["Parameter", "Value"]]

        for key, value in filtered_inputs.items():
            input_data.append([
                Paragraph(str(key), wrap_style),
                Paragraph(str(value), wrap_style)
            ])

        input_table = Table(input_data, colWidths=[220, 250])
        input_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))

        elements.append(input_table)
        elements.append(Spacer(1, 20))

        elements.append(PageBreak())

        # -------- Clean Outputs --------
        clean_outputs = {k: get_field_value(v) for k, v in output_fields.items()}

        # -------- Outputs Table --------
        elements.append(Paragraph("Results", styles['Heading2']))
        elements.append(Spacer(1, 12))

        output_data = [["Output", "Value"]]

        for key, value in clean_outputs.items():
            output_data.append([
                Paragraph(str(key), wrap_style),
                Paragraph(str(value), wrap_style)
            ])

        output_table = Table(output_data, colWidths=[220, 250])
        output_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))

        elements.append(output_table)

        # -------- Build PDF --------
        doc.build(elements)

        print(f"PDF saved at: {file_path}")
        return True

    except Exception as e:
        print("PDF Error:", e)
        return False


def show_whats_new(self):
    """Displays information about new features."""
    print("Action: What's New?")
    QtWidgets.QMessageBox.information(self, "What's New?",
                                    "Version 1.0.1\n\n"
                                    "- Implemented combobox selection logic.\n"
                                    "- Added action button functionality.\n"
                                    "- Console output for all inputs.\n"
                                    "- Corrected Barlow Stress calculation formula.")

def show_documentation(self):
    """Displays application documentation."""
    print("Action: Documentation")
    QtWidgets.QMessageBox.information(self, "Documentation",
                                    "Detailed documentation will be available here.\n"
                                    "For now, please refer to the input labels for guidance. (Placeholder)")
    # You could open a local PDF/HTML file or an online link here
    # Example: QtGui.QDesktopServices.openUrl(QtCore.QUrl("file:///path/to/your/documentation.pdf"))
    


def reset_all_inputs(self):
    """Resets all input fields, comboboxes, and radio buttons to their default states."""
    print("Resetting all inputs...")
    # Clear all line edits
    for line_edit in self.findChildren(QtWidgets.QLineEdit):
        line_edit.blockSignal(True)
        line_edit.clear()
        line_edit.blockSignal(False)

    # Reset comboboxes to default index (0)
    # for combo_box in self.findChildren(QtWidgets.QComboBox):
        # combo_box.setCurrentIndex(0)

    # Uncheck all radio buttons
    # self._uncheck_all_radio_buttons()

    # Re-initialize default numerical values (which now clears them)
    # self.initialize_default_input_values()
    print("All inputs have been reset.")
    
    

def saveAs(saveData):
    print(f"\n\tSaving file....!!!")
    try:
            
            filepath = filedialog.asksaveasfilename(
            # os.getenv('home'),
                    initialdir= "C:/Users/DELL/Desktop",
                    title= "Save As",
                    defaultextension= "*.csv",
                    filetypes=(
                            ("csv file","*.csv"),
                            ("HTML file","*.html"),
                            ("text file","*.txt"),
                            ("All file","*.*")
                    )
            )
    except:
            print(f"error code:{random.random()}>>>>>>Error in saving file while opening to write..$$%%^^&&&")
    try:
            if filepath is None:
                    return
            else:
                    with open(filepath, 'w'):
                            df = pd.DataFrame({"SL no" : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29], "INPUTS": saveData.keys(), "Values": saveData.values()})
                            df.to_csv(filepath)
    except:
        print(f"error code:{random.random()}>>>>>>ERROR in saving your file...!!")
        QMessageBox.warning(None, "Warning", 'File is not saved..!!!!')
        




def open_screen(screen_class, *args, **kwargs):
    try:
        screen = screen_class(*args, **kwargs)
        screen.show()
        return screen
    except Exception as e:
        print(f"Error opening screen: {e}")
        return None